### ISSUE TITLE
[5.09.29] Minor exploit with Programmed Circuit

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#1027]
There are easy way to convert Electronic Circuit to Integrated Logic Circuit via Programmed Circuit.

**Comment by JohannesGaessler** [comment]
Is there any benefit to doing that?
As far as I can tell Electronic Circuit > Logic Circuit in all situations.
Like you can hand craft Advanced Circuits from Electronic Circuits but not from Integrated Circuits.

**Comment by SapientMC** [comment]
Good Integrated Circuit and Advanced Circuit could be made from Integrated Logic Circuits but not from Electronic Circuit.

**Comment by JohannesGaessler** [comment]
You wouldn't be able to exploit that.
The whole point of Logic Circuit <-> Electronic Circuit is that your basic circuits become much cheaper once you get a Basic Circuit Assembler.
Good Integrated Circuits become available at the same time that Electronic Circuits become obsolete.
In fact I'd say this mechanic is even a good thing because it allows you to convert any old circuits you have into the new type.

**Comment by SapientMC** [comment]
Seems you right.
