### ISSUE TITLE
Feature Request: Config Option to disable ore variants

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#1061]
would it be possible to add config options to disable ore variation (such as granite, marble, small) ores from being enabled?

**Comment by Antifluxfield** [comment]
Those small ores should not be considered as a variation like granite or something. They are quite different from the regular ores.

**Comment by draknyte1** [comment]
Some people may not want them. I'd say it's a valid suggestion.. easily added as well

**Comment by MauveCloud** [comment]
Small ores can already be enabled/disabled separately in the config.  However, I tried that once, and discovered that in 5.09.29, with otherwise default WorldGeneration config, removing the small ores creates a tech loop: (tiny) gallium dust for diodes for crafting MV-tier circuits (needed for LV-tier circuit assemblers, and none of the higher-tier circuits can be made in a crafting table) is only available as the 3rd byproduct of bauxite or sphalerite ore, which needs the HV-tier universal macerator to obtain, which in turn needs gallium dust along the path toward making it.  

Zinc ore has gallium dust as a 2nd byproduct, so crushed zinc ore from the small ore can be put in an LV ore washing plant and then an LV centrifuge to get tiny gallium dust.  I don't think any of the other small ores are similarly critical, though.

**Comment by ghost** [comment]
I believe the tiny pile issue was solved in version 5.10, when checking the recipe for tiny dusts and small dusts you can place the dust in the top left or middle of a crafting table to get the respective dusts.

**Comment by MauveCloud** [comment]
@lolorz13 are you sure you're commenting on the correct bug?  There was no mention of a tiny pile issue in the recipes here.  Also, being solved in version 5.10 generally doesn't help with closing 5.09 bugs, since that's a semi-independent branch for a different version of Minecraft, while 5.09 development is still ongoing.
