### ISSUE TITLE
Hitbox

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#109]
Is it possible to reduce the Hitbox to not be a full block?
Because right now its impossible to access the Input / Output Bus/Hatch on machines if a Item / Fluid Pipe is connected.

**Comment by pyure** [comment]
This would be glorious but I suspect its virtually impossible due to the way greg uses TEs.

**Comment by Blood-Asp** [comment]
Yes, MetaTileEntitys make it quite difficult to change the hitbox size. It should still somehow be possible, but so far i did not find a way to do it withing 2h of trying.

**Comment by pyure** [comment]
Its a shame.  GT is really backwards in this regard, and I doubt GT6 will fix it either.

Well, fingers crossed :)

**Comment by LuxusDarkangel** [comment]
I think you shouldn't fix that, just because Greg wanted it to work like that, as you can see in his Q/A:

"Q: Would you please fix the hitboxes of your Pipes and Wires to not be a full Cube?
A: Nope. While I know exactly how to "fix" that Problem properly, I am not going to do that. It is FULLY INTENDED to no be able to access GUIs of things which are right next to a Pipe, or to place Blocks behind Pipes. You could not do that IRL, so you won't be able to do that in GT either, like some other Mods do."

**Comment by pyure** [comment]
Meh, if you know Greg, that's just his lazy reasoning.  Its actually a really hard problem to address with the way he's set up his blocks, and I don't blame him for not putting a lot of effort into it.

While sometimes it makes a bit of sense for a gigantic "large tungstensteel pipe" to obstruct physical access, 90% the issue is actually a case of a tiny straw-sized pipe obstructing visual access (WAILA, etc).  That certainly doesn't make sense.  

And at the end of the day, the "sense" is totally irrelevant because the vast majority of other mods do it better, and in a way that is more appealing to gamers.
