### ISSUE TITLE
Processing Array

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#110]
The processing array does not process multiple item types at the same time (only 16 items from 1 stack).

(The multi smelter can process 18 different items at the same time.)

gregtech_1.7.10-5.08.25

**Comment by Blood-Asp** [comment]
Thats intended behavior for the array. All machines are syncronized and only can do the same. Also if you not noticed, when only processing one item at once, but having 16machines inside, it uses 16x the energy it would need as singleblock.

And the technical explanation: The Array is meant to replace huge amounts of machines doing the same, primary the centrifuges for a fusion reactor. To make as much sense as possible, i want it to use as little processing time as possible, so i do only one recipe search for all machines, effictively reducing the lag produced from the multiblock to be the same as about 3-4 single block machines instead of 16, and also saving processing power on connected cables and pipes.
