### ISSUE TITLE
Broken material formulas

### ISSUE THREAD

**Issue by MineWitherMC** [Blood-Asp/GT5-Unofficial#1106]
1. Red Alloy has formula `?(Si(FeS2)5CrAl2O3Hg3)4`, but should have `Cu(Si(FeS2)5CrAl2O3Hg3)4`
2. **Tungstencarbide has `W` instead of `WC` (bug appeared at some moment after .27)** (most important IMO)
3. Lazurite has `Al6Si6Ca8Na8` instead of `Al3Si3Ca4Na4` (not empirical for some reason), same for Realgar `As4S4` (but this is probably intended) and Pollucite `Cs2Al2Si4(H2O)2O12`
4. Dark Ashes misses formula at all, breaking some others (e.g. Lignite `C2(H2O)4C` => `C2(H2O)4?` and Blaze Powder `CSMa` => `?SMa`)
5. Fireclay should have `Al4Si3O12Na2LiAl2Si2(H2O)6`, `Al6Si5O12Na2Li(H2O)6` or something like that, but has `Al4Si3O12`
6. Hydrated Coal's `(C)8H2O` formula is silly (probably happened after Diatomite fix)
7. Zeolite `NaCa4Si27Al9(H2O)28O72` doesn't separate properly, resulting in fluids loss (probably it's because too much zeolite in 1 stack?)
8. Diatomite has sapphire in processing results, is that intended?

**Comment by JohannesGaessler** [comment]
~The Fireclay formula is intended; It's still missing Water but I haven't yet decided on how much.
The Clay Formula is wrong and I will probably change it at some point in the future.~

Also it's not necessarily correct to reduce chemical formulas as much as possible.
For instance Phosphorous Pentoxide has (despite its name) the chemical formula P4O10 because that is the formula of its repeating unit.

**Comment by JohannesGaessler** [comment]
Fixed 1, 2, 6 via 41b93ae85dfe8e15f7d46a09cb49b65991901fed

**Comment by Techlone** [comment]
@JohannesGaessler look at https://github.com/Blood-Asp/GT5-Unofficial/issues/885

**Comment by JohannesGaessler** [comment]
@Techlone I think giving Tungstencarbide a wong formula is a poor fix for that problem.
I think a better solution is to disable automatic centrifugation for Tungstencarbide and add a special recipe.

**Comment by draknyte1** [comment]
The centrifuge recipe for WC is correct, the EBF recipe is not.
WC is 1/2 W and 1/2 C, so combining one of each should net two ingots as anything else does.

**Comment by mura3277** [comment]
@JohannesGaessler What's the status on this?

**Comment by JohannesGaessler** [comment]
1, 2, 6 have been fixed.
3 is debateable. Either the empirical formula or the formula of the repeating unit can be seen as correct.
4 is debateable. Since I changed the components of Ash the formula for Ash/Dark Ash would be very long and unhelpful. So I think not giving Ash/Dark Ash a formula is preferable, even if there are some question marks in other formulas.
I've changed my mind on 5. Removing Lithium and Sodium from Clay would make producing Batteries too tedious. I will change the formula for Fireclay.
7, 8 have not been touched by me.
