### ISSUE TITLE
[5.09.31pre1] Producing Biomass in Brewing Machine are faster and cheper then in Pyrolyse Oven

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#1134]
Pyro Oven: 5000 / 45 = 111.1 L/sec; 9000 / 5000 = 1.8 eU/L
Brewer: 750 / 6.4 = 117.2 L/sec; 512 / 750 = 0.68 eU/L
![image](https://user-images.githubusercontent.com/14032818/27765346-edcefde0-5eae-11e7-8485-94238a1bcbe0.png)
![image](https://user-images.githubusercontent.com/14032818/27765351-ffebf514-5eae-11e7-87d1-a36c7026f4e0.png)

**Comment by abculatter2** [comment]
Considering the Pyrolysis Oven (It should be Pyrolysis btw, not Pyrolyse) already has some rather significant uses, I personally feel that it really doesn't need to be the best at this, as well. I'd personally just make it a minorly less energy efficient then the brewer, and significantly faster.

**Comment by mura3277** [comment]
@abculatter2 While I agree with this a lot of players will see both recipes and automatically assume the Pyro oven is the better solution since it's a "large machine".

Also since this is kind of on-topic: @JohannesGaessler Maybe biomass recipes from various organic items should be added to the GT fermenter or pyro oven similar to how Forestry does it?

**Comment by Blood-Asp** [comment]
Fixed for .31
