### ISSUE TITLE
New blast furnace metal processing dupe

### ISSUE THREAD

**Issue by Usernm0** [Blood-Asp/GT5-Unofficial#1181]
Sulfur processing dupe items, and give nothing in output hatch. I test it with galena->Massicot, and pyrite -> banded iron. Second stage with carbon works fine. I try to remove output hatch from top, and dupe still works. 
EBF setup if needed:
![](http://i.imgur.com/E31y1xt.png)
[Twitch clip](https://clips.twitch.tv/HealthyObedientDragonWutFace)

**Comment by draknyte1** [comment]
This is probably a new Horizons issue.
I'm not sure what recipe you're processing (try turn your texture pack off) but if that's one after the blast furnace changes then it's not our issue because we haven't even merged it into gregtech yet. @Dream-Master merges things as soon as they're suggested which leads to these issues.  
@JohannesGaessler maybe you should investigate if it's from your 'proposed' changes.

**Comment by JohannesGaessler** [comment]
This bug was introduced by https://github.com/Blood-Asp/GT5-Unofficial/pull/1170 and only manifests in the GTNH version of GT5U.
I have since developed a fix though I haven't yet heard from Dreammaster whether he can confirm that it works.

**Comment by draknyte1** [comment]
Yeah thought so.

**Comment by Dream-Master** [comment]
@Usernm0 Gtnh 1.5.0.8 will fix that asap

Bugs on GTNH fork of GT aon be post here
https://github.com/GTNewHorizons/GT5-Unofficial
