### ISSUE TITLE
[Balance Suggestion] Industrial Daimonds via Compressor

### ISSUE THREAD

**Issue by ChubbyTurtle101** [Blood-Asp/GT5-Unofficial#1246]
It is nice to have an alternate recipe to get industrial diamonds from the compressor instead of the implosion compressor so you don't have to do creeper killing grind just to get gun power.  TNT is impossible at this stage unless you are lucky enough to find dungeon chests.  On my world dungeon chests seem to be hard to find (bad RNG).  The issue is the recipe currently only takes 2EU/tick in 5.09 which is extremely cheap.  The time is fairly fast also.  Total EU is less than some ore washing recipes. It should require at least a HV Compressor (~200 EU/tick) and an extremely long period of time to compress the coal chunk ball into a diamond.  This way it would be more efficient to use the implosion compressor once you can make TNT or have enough gun power.  If the RNG gods are not with you then you can do it through a compressor but it is going to cost quite a bit of power and time.

You already need HV power for the first highly sought after HV machine - the HV Macerator which requires an industrial diamond.

**Comment by MauveCloud** [comment]
>  TNT is impossible at this stage unless you are lucky enough to find dungeon chests.

How do you figure that?  I admit the processing recipes can be a little confusing and daunting at first, but it looks to me like TNT can be made even if you only have LV machines.

Side note: I was not aware TNT generated in dungeon chests (the Minecraft wiki doesn't mention it), though maybe you have a mod that generates it there; otherwise you might have better luck looking for it in desert temples.

**Comment by ChubbyTurtle101** [comment]
Even though the recipes are LV for TNT, it requires a significant petrol setup.  So far my only source of oil that I have found is oil sands which are used for plastic (Polyethylene) which requires ethylene.  Without a multiple distillation tower setup, you get every little ethylene for the oil used.  For TNT I need sulfuric acid and gelled Toluene.  I am still working to get the infrastructure to deal with the Hydrogen Sulfide cells in my basic ethylene setup.  My comment was regarding the alternative recipe for the industrial diamonds which uses the basic compressor which only takes 600 EU at 2 EU/tick to compress a coal chunk into an industrial diamond.  This recipe is just too cheap.  I like having this alternative but is should be more expensive in needing a higher tier compressor and the amount of EU needed.   

Also I believe you are right that TNT is found in desert temples.  I have had a difficult time generating a world where there was a desert anywhere close to my base.  At least I have a large area of extreme hills.  for the record this is not a complaint about the new chemical update, I just think the compressor industrial recipe is just not balanced.

**Comment by bear989** [comment]
Industrial diamonds can be made in the compressor and I never understood why they were re added, and you can also use dynamite witch i believe is completely do able in LV as well and doesnt take oil products.
![2017-10-12_23 57 34](https://user-images.githubusercontent.com/8433695/31529786-76a4a7b4-afa9-11e7-9665-87b1de3868e9.png)

**Comment by MauveCloud** [comment]
So glycerol doesn't count as an oil product even though it takes fish oil or seed oil to make it? :smile:

**Comment by bear989** [comment]
no, no it doesnt.

**Comment by Antillar** [comment]
@MauveCloud TNT generates as a part of Desert Temples. It can also be found in dungeon chests, but with very low probability.

Note that there is an online app to find Desert Temples based on world seed.

**Comment by Antillar** [comment]
And I have to agree with others that TNT is very easy on LV, considering that oil processing setup is already done. Toluene is only one step from the line of materials which you need to automate to get plastic. And you get TNT from toluene very easily.

TBH, at any point it is better to make Industrial TNTs than normal TNTs, they are almost the same in the cost of resources, but the former one is 2 times better in recipes.

**Comment by MauveCloud** [comment]
@Antillar Are you sure the TNT isn't being added to dungeon chests by a mod?  Considering that https://minecraft.gamepedia.com/Chest_loot has a table with exact random weighting down to 2/127 for enchanted golden apples in dungeon chests (or 2/232 in desert temple chests), I seriously doubt they missed TNT being generated in these chests in vanilla Minecraft.

Also, as far as making TNT at LV, after looking at the recipes in NEI, now I'm not so sure it's quite that easy - for making ethylene (toward polyethylene), severely steam-cracked naphtha or severely steam-cracked light fuel look like the best choices, giving 500 L or 250 L ethylene per 1000 L respectively, but distilling these for toluene only gives 20 L or 30 L respectively, and 400 L are need to make enough gelled toluene for 1 tnt.  Industrial TNT may have similar resource cost, but significantly higher infrastructure cost (since it requires an HV chemical reactor or a large chemical reactor running at HV to make it).

However, that's getting a bit off track.  I think the main issue was that industrial diamonds are too easy to make, since coal chunks can even be put into a steam compressor to get them.  I can only guess that maybe it was added for players who had too much trouble finding their first diamonds for a steam macerator (or maybe were playing skyblock maps), but I don't see why this has to make an industrial diamond in a regular compressor - it seems like it could be changed to return a regular diamond instead, so that industrial diamonds still require the implosion compressor (using either diamond dust or coal chunks).  

Oh, one other thing I can mention: if dynamite and (industrial) tnt are too much trouble, a "creeper killing grind" is not the only way to get gunpowder - you can also mix coal/charcoal/carbon dust, sulfur, and saltpeter to make it, or grow creeperweed.

**Comment by draknyte1** [comment]
We've discussed changing industrial diamonds previously and decided we wont change it.

**Comment by Antillar** [comment]
@MauveCloud Many of the players have Railcraft installed along with GT, mainly from older versions when it was extremely hard to get to steam age because of the absence of BBF. So do I. I am definitely sure that TNT carts are added to dungeon loot by Railcraft. Not entirely sure about pure TNT though, but TNT carts can be easily turned into TNT.

I am not a big expert of chemistry after .31, so you may be right about the cost of toluene. However, powderbarrels are ok too. And those require the most basic mob grinder to be able to obtain. On my LP series I made a standart 4-floor 16x16 darkroom mob grinder. It stayed for less than 100 hours, and then it was deconstructed to free the space. At this point in time I had 70k gunpowder. So I totally went with powderbarrels until I was able to easily produce ITNT.

**Comment by MauveCloud** [comment]
@Antillar I just searched through the Railcraft source code, and it looks like it adds TNT carts to the chest carts in Mineshaft corridors and chests in village workshops, not dungeons.  Those can sometimes be easier to find than dungeons (though I admit I have yet to find either mineshafts or dungeons in my current world - I have found three villages, one of which has a workshop, but no TNT carts in the chest).

**Comment by NNM42** [comment]
hmmm, if i disabled structures and playing wo RailCraft...

**Comment by PrincessOfEvil** [comment]
Desert temple has 9 placed tnt.
