### ISSUE TITLE
GT5u pipes, they suck!

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1253]
we all know this, that is why most people use EIO conduits for piping fluids. but the GT6 pipes are sooo much better! they can use covers just like GT5, they still slosh but with a destination pathing, no auto connections, and quad and nanople pipes for multiple fluids in a single block. my iss is a suggestion to back port the GT6 fluid pipes to GT5u.

**Comment by draknyte1** [comment]
Probably not.

**Comment by MauveCloud** [comment]
I have not used GT6 pipes or EIO conduits for piping fluids, but I notice the tooltip for the "Ender Fluid Conduit" says "Max IO: 800 MB/t" which comes to 16000 L/sec, and many GT5u pipes can already theoretically exceed that throughput.  I am willing to believe that GT6 pipes are better, but afaik GT6 is still closed-source, so don't we need to ask Greg's permission before porting them to GT5u?

**Comment by leagris** [comment]
Pumping all steam from a Bronze boiler (lowest tier), requires:
2 LV Fluid Output Hatches
2 distinct and unconnected lines of Large Steel Fluid pipes
a shutter module for each pipe section.
IIt is quite bulky and costly with materials.

Here is the cleanest setup I could come-up with:
Pipes are covered with wood covers to prevent heat damage on contact and to prevent both pipelines to connect. It is only 3 blocks long but uses a total of 8 Shutter Modules (yes need it even on fluid output buses so steam don't try to re-enter from the pipes). 
![lbb_steam_out](https://user-images.githubusercontent.com/1111474/31776314-6f928cd8-b4eb-11e7-982c-bedf4b9ccdfc.png)

Material cost was:
8×4=32 iron plates for Shutter Modules
6×6=36 steel plates for large steel fluid pipes.

**Comment by draknyte1** [comment]
GT6 pipes wont be backported and if someone wants they are free to rewrite them from scratch to closely immitate 6s.

Permission from Greg for this was denied in the past.

**Comment by MauveCloud** [comment]
@leagris, I think you might be overestimating the need for shutter modules.  Using this setup:
![2017-10-19_08 18 18](https://user-images.githubusercontent.com/8942955/31778982-e8bbe2c0-b4a6-11e7-9c48-4b128f39e267.png)
with "Circuitry burned out" (since I haven't made a soldering iron yet), I still got 18214800 steam using 10 stacks of charcoal from a cold start.  Calculating for maintenance inefficiency, I presume I'm getting 28800 steam per charcoal at full heat, which would be potentially 18432000 from 10 stacks.  The missing 217200 steam is more likely from the warmup time than issues with sloshing mechanics or steam going into an output hatch (which doesn't actually happen - I tried putting an independent output hatch on a pipe with steam, and the steam doesn't go in, even with the opening pointed toward the pipe)

Also, once you can reach production of other fuel types, much less throughput is needed - a single LV steam turbine needs 1600 steam/sec, but with natural gas only 195.6 L/sec is needed for MV, and other fuels get better from there.

**Comment by bear989** [comment]
well something desperately needs done with pipes in GT5u, they are horrible, for people trying to use minimal of outside mods it can become a huge mess with the auto connecting and endless sloshing they do.

**Comment by leagris** [comment]
I always thought pipes could only connect when placing a rubber ring as seal on face.
I would also get ride of the shutter requirement and allow defining the direction of a face with a screwdriver.
Would not create deep changes into fluid pipes mechanics.
Shutters would stil be relevant as Redstone controlled valves.

**Comment by draknyte1** [comment]
You guys can ask for change all you want but nobody has been or is currently interested in doing it. 

Rubber pipe seals? What?..

**Comment by leagris** [comment]
No change in shutters. Those in-place doing their job
No additional item. Re-use rubber rings as pipe connector seals.
Existing pipe setups needs be defined outcome. Maybe update already placed tile to include seals at connectors. Existing pipes probably have no defined face direction so they behave exactly the same as before change.
Screwdriver on face could cycle between:
1. Both ways (default)
2. Output
3. Input

Another possibility is to not add seal rubber ring.
Allow face to define connexion with a 4 states screwdriver cycling.
1. Default to not connected
2. Connected output
3. Connected input
4. Connected both-ways

Already placed in-world pipes would be considered state 4 connected both-ways.

This would fix:
- Shutter spamming
- Unwanted pipe connexions

**Comment by MauveCloud** [comment]
Here's my more detailed analysis of this:
1. I have little experience with pipes from other mods, except maybe BuildCraft, so some of my other points could be wrong.
2. Pipes from other mods might not be entirely immune to "sloshing" either (BuildCraft pipes certainly aren't - and the sloshing is visible for them), but I like the idea of using a screwdriver (or maybe a wrench, since this is plumbing) to adjust connections instead of having them connect automatically, and having some inherent directionality without requiring a full shutter module would be nice (though for balance, perhaps have separate "directional pipes" crafted with rubber/paper rings, depending on the pipe tier)
3. Once pipes are full, sloshing becomes a non-issue.  If players have trouble with this, it may mean they're not buffering fluids enough (which I'll admit can be difficult without other mods such as Railcraft for its iron/steel tanks) or the fluid consumers are too close to the limit of the pipe's throughput (e.g. having 6 or more LV steam turbines supplied by one sequence of large steel pipes)
4. In a few cases, pipes can be omitted by transferring fluids directly from machine to machine (or tank).  For example, I changed my large bronze boiler setup to be directly adjacent to my steel tank and use one output hatch pointed directly at a steel tank valve, and the steam amount in the output hatch remained steady at 800 while it was running, indicating I wasn't losing any steam due to inadequate pipe capacity.
5. Pipes from other mods often lack temperature restrictions, or only apply them to the lowest tier, making them feel like cheats - e.g. GT5u has special "plasma containment pipes" that require expensive materials like magnetic neodymium and superconductor wires, but the Hardened Fluiduct from Thermal Dynamics has no temperature restrictions according to the FTB wiki, and "the rate at which it transports fluids is inversely proportional to the Viscosity of the fluid being transported."  NEI Integration tells me helium plasma has viscosity 10 compared to 1000 for water, so presumably I'd be able to transport plasma 100 times as fast as water.  Perhaps this isn't much of a cheat, though, since plasma can already be put in empty cells made from tin and other materials, and then transported by other means (including GT5u item pipes - if my calculations are correct, with enough cells and some HV fluid canners (which can run at LV since getting fluids into/out of cells costs 1 EU/t by default), a brass item pipe can have an effective fluid speed of 20000 L/sec, making almost a match for a large tungstensteel fluid pipe)

**Comment by leagris** [comment]
#### Improved my proposition:

- Change face directionality with wrench right-click:  
  1. `state=0 or undefined` (Default state) Same as current pipe connection:  
  It would attempt connection and bidirectional fluid transfer.
  Chat message: `Output, accept input`
  1. `state=1` Output state active push:
  It would attempt connecting adjacent fluid container/pipe/machine,  but will refuse input.  
  It means it will not connect with adjacent pipe if its face is also `state=1`. Although, it would connect to a pipe on default `state=0`
  Chat message: `Output only`
  1. `state=3` Closed:
  It would deny all connexions.
  Chat message: `Closed`

##### Combinations of adjacent face states:

<table>
  <thead>
    <tr>
      <th colspan="3">Pipe A</th>
      <th colspan="3">Pipe B</th>
    </tr>
    <tr>
      <th>State</th>
      <th>Connect</th>
      <th>Transfer</th>
      <th>State</th>
      <th>Connect</th>
      <th>Transfer</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan="3">undefined</td>
      <td>yes</td>
      <td>both</td>
      <td>undefined</td>
      <td>yes</td>
      <td>both</td>
    </tr>
    <tr>
      <td>yes</td>
      <td>in</td>
      <td>output</td>
      <td>yes</td>
      <td>out</td>
    </tr>
    <tr>
      <td>no</td>
      <td>none</td>
      <td>closed</td>
      <td>no</td>
      <td>none</td>
    </tr>
    <tr>
      <td rowspan="3">output</td>
      <td>yes</td>
      <td>out</td>
      <td>undefined</td>
      <td>yes</td>
      <td>in</td>
    </tr>
    <tr>
      <td>no</td>
      <td>none</td>
      <td>output</td>
      <td>no</td>
      <td>none</td>
    </tr>
    <tr>
      <td>no</td>
      <td>none</td>
      <td>closed</td>
      <td>no</td>
      <td>none</td>
    </tr>
    <tr>
      <td rowspan="3">closed</td>
      <td>no</td>
      <td>none</td>
      <td>undefined</td>
      <td>no</td>
      <td>none</td>
    </tr>
    <tr>
      <td>no</td>
      <td>none</td>
      <td>output</td>
      <td>no</td>
      <td>none</td>
    </tr>
    <tr>
      <td>no</td>
      <td>none</td>
      <td>closed</td>
      <td>no</td>
      <td>none</td>
    </tr>
   </tbody>
 </table>

This is 100% backward-compatible with existing Worlds.
This is coherent with using screwdriver on a machine face to disable it (as implemented in Gregtech4)

Rendering visual clue either using texture or adapting model to reflect face state (even on pipe side border would be an appreciated improvement.
Default state would render same connected.
Output state could render same but always with a connexion extension even if no adjacent block.
Closed state would show a closed plug or diagonal cross (or whatever texture is appropriate for a given pack).

**Comment by popbangshwang** [comment]
How much would it cost to actually have someone fix this? The way pipes work in GT5 is the most frustrating thing, fixing it would drastically improve the playing experience.

**Comment by OvermindDL1** [comment]
Aren't the only difference between GT5u and GT6 fluid pipes just that the pipes do not auto-connect in GT6 and that the fluid remembers it's flowing direction a 'little' differently (and it auto-balances on a modulus 2 of the x/y/z position to it's output directions)?  Shouldn't that be quite easy to port or is there something else?

_/me does *not* like EIO pipes as they are *way* too magical and powerful in operation and way too cheap for what they do_

And yes, Greg did give permission, I don't know why @draknyte1 thinks otherwise, I even have it here in my IRC logs:

```irc
<bear989> greg I have been sent to beg, can someone who knows how to code use your pipes from GT6 in GT5u?
<@GregoriusTechneticies> sure if you can find someone who does it XD
```

I doubt he would really say no about anything like that anyway...  o.O

**Comment by OvermindDL1** [comment]
Also, don't forget that the fastest GT5 way to transfer fluids via a pipe-like thing is to use machine hull's (that imagination one) and cover it in pumps, nothing moves fluids faster in any mod I've seen in raw throughput, even AE's fluid transfer things limit their throughput based on various conditions.  That is if you really need to transfer like 20 buckets a tick I think it was.  ^.^;

**Comment by SuperCoder7979** [comment]
We got permission from Greg to use his code in GT5u, if anyone wants to do it

**Comment by jaskarth** [comment]
yes, the major problem everyone's been having is that the pipes autoconnect forcing you to waste materials on covers. If we all come together to port Greg's code we can probably do it. the only problem is that Greg in GT5 decided to be lazy and make one god MetaTileEntity class that everything inherits from. Also, according to Alkalus GT5 thinks wires are "pipes" as well, so that would probably mess up the wires as well. Not to mention adding some more functionality to wrenches and wirecutters

**Comment by draknyte1** [comment]
@OvermindDL1 I have asked previously and got told no..

**Comment by SuperCoder7979** [comment]
Maybe it was because Bear asked him, but we have permission from Greg, now we just need to fix everything :p

**Comment by jaskarth** [comment]
@GregoriusT, can we have your final word on whether we are allowed to use your GT6 pipe code in GT5u?

**Comment by GregoriusT** [comment]
Can you please tell me when I told you "No"? Like a Date on the Calendar? So I can look it up on my IRC Logs, to see how I worded it.
Because copyright wise, I hate "technology based copyright" or "patent right", both are just obstacles for everyone and hinder progress.

**Comment by draknyte1** [comment]
Two reasons why I cant.

Im on holidays with no access more than a phone & I wouldve asked through Espernets web client.. havent bothered keeping IRC logs for 6 month+.

Considering my lack of IRC activity in that time, you should be able to find it. Anything older I can pull up when I get back to Aus in a few weeks.

**Comment by GregoriusT** [comment]
Well, you are allowed to use my code to improve your Pipes, I really dont have anything against usage of my code, all I would say about it is "make sure you do it right", since my GT6 Stuff is very different from GT5 Stuff. ;)
