### ISSUE TITLE
recipe needs deleted

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1285]
![2017-11-13_20 56 20](https://user-images.githubusercontent.com/8433695/32759014-3ff0f7b6-c8b5-11e7-97ff-e9560ba638fd.png)

**Comment by Blood-Asp** [comment]
The Carbon für Just has a Burnvalue in the vanilla furnace. It is too low to be usabe in large furnace but has its reasons there.

**Comment by bear989** [comment]
why does carbon have a burn value in a furnace?! you cant burn carbon
straight

**Comment by MauveCloud** [comment]
> The Carbon für Just has a Burnvalue in the vanilla furnace. It is too low to be usabe in large furnace but has its reasons there.

Are you sure about that?  https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/GT_Proxy.java#L1451-L1553 does not add it, and I turned on NEI Integration's option to show furnace burn times, so now I find that carbon dust does not have one as you claim (unless added by a mod I don't have).

**Comment by draknyte1** [comment]
We removed the burn value ages ago.

**Comment by jaskarth** [comment]
Nope, it still exists. I just checked using a dev version. Also, there is a dupe for carbon using an ender IO alloy smelter, where inputting 1 carbon dust results in 2 carbon ingots. 
![image](https://user-images.githubusercontent.com/25208576/32975281-d4091f52-cbd3-11e7-832b-4aabbf40741a.png)

**Comment by draknyte1** [comment]
NEI always shows EIO alloy smelter recipes incorrectly.

**Comment by JohannesGaessler** [comment]
This recipe is my fault.
Because I did not find a sensible way of iterating over burnable solid fuels I chose to instead explicitly add a few solid fuels to the NEI tab with a notice that anything that burns in a vanilla Furnace will burn in a Large Boiler.
At the time Carbon Dust had a burn value.
When the burn value was removed I forgot to remove the NEI entry for Carbon Dust and that's where this recipe comes from.

Unrelated to that, in real life carbon dust would burn quite well and I really don't understand why so many believe that it doesn't.
