### ISSUE TITLE
GT6 Style Wires

### ISSUE THREAD

**Issue by danbka33** [Blood-Asp/GT5-Unofficial#1331]
If you restart the server after you connect the wires, all connections will be reset

**Comment by Dream-Master** [comment]
There is a pull request from Antiflux.  I guess this will fix the issue hopefully.

**Comment by danbka33** [comment]
Forgot to say, I already applied this PR. This did not solve the problem.

**Comment by Dream-Master** [comment]
@Antifluxfield any idea ?

**Comment by mitchej123** [comment]
Potential fix from downstream https://github.com/GTNewHorizons/GT5-Unofficial/pull/62

I'll rebase on this repo and submit a PR once it's tested.

**Comment by draknyte1** [comment]
@mitchej123 looking through yours and https://github.com/Blood-Asp/GT5-Unofficial/pull/1329/files briefly and they look to solve the same issue. Why is yours superior to the one written by this features original author?

**Comment by mitchej123** [comment]
I've had success with the wire fix locally so far.  It depends on https://github.com/Blood-Asp/GT5-Unofficial/pull/1329  so it'll either need to be absorbed into 1329, or created & merged after.

**Comment by Antifluxfield** [comment]
Try with the latest #1329 to see whether it works...

**Comment by mitchej123** [comment]
I pulled in your specific cable changes here: https://github.com/mitchej123/GT5-Unofficial/commit/d458c0499b7ba28872d74ebce57b49a5b88307ea  (basically commented out the -1 because of energy state unloaded but still tracked it, and added the if chunk unloaded)

No luck on either world load or chunk unload/reload.  The debug messages were:
```
Energy state not ready
Tile Debug: tEnergyConnected:true tEnergyInOrOut:false  # <--- This one should be all trues
         tIsTileEntity:true tIsTileEntityCable:false AlwaysLookConnected:false LetEnergyIn:true LetEnergyOut:true
         tIsEnergySink:false tSinkAcceptsEnergyFromSide:false
         tIsEnergyReceiver:false tEnergyReceiverCanAcceptFromSide:false
Self - AlwaysLookConnected:false LetEnergyIn:true LetEnergyOut:true
Was connected - Now disconnecting.  CheckConnections: false
```


To test - I built an EBF in creative with an energy input hatch feeding from a battery buffer.  Said battery buffer is connected with one cable on top to 3 turbines. Both were disconnected when loading in, and after connecting & chunk unload/load [run away and back].

**Comment by mitchej123** [comment]
The underlying issue is this bit of code from BaseMetaTileEntity

```java
    @Override
    public boolean inputEnergyFrom(byte aSide) {
        if (aSide == 6) return true;
        if (isServerSide()) return (aSide >= 0 && aSide < 6 ? mActiveEUInputs[aSide] : false) && !mReleaseEnergy;
        return isEnergyInputSide(aSide);
    }
```

If server side it looks at mActiveEUInputs or mActiveEUOutputs.  They are initialized to false, and not updated immediately on chunk load, but roughly 20 ticks after in updateEntity.  

```java
private boolean[] mActiveEUInputs = new boolean[]{false, false, false, false, false, false}, mActiveEUOutputs = new boolean[]{false, false, false, false, false, false};
  public void updateEntity() {  // Highly <snipped>
        try { for (tCode = 0; hasValidMetaTileEntity() && tCode >= 0; ) {
            switch (tCode) {
                case 10:
                    tCode++;
                    if (aSideServer) {
                        if (mTickTimer > 20 && mMetaTileEntity.isElectric()) {
                            mAcceptedAmperes = 0;
                            if (mMetaTileEntity.isEnetOutput() || mMetaTileEntity.isEnetInput()) {
                                for (byte i = 0; i < 6; i++) {
                                    boolean
                                            temp = isEnergyInputSide(i);
                                    if (temp != mActiveEUInputs[i]) {
                                        mActiveEUInputs[i] = temp;
                                    }
                                    temp = isEnergyOutputSide(i);
                                    if (temp != mActiveEUOutputs[i]) {
                                        mActiveEUOutputs[i] = temp;
                                    }
                                }
                            }
```

I was pondering just changing `inputEnergyFrom` to always report current state; but I don't have the historical context as to why it was done this way and what else would break if changed.

**Comment by Antifluxfield** [comment]
@danbka33 So you ONLY lost the connections between cables and machines(or hatches), not "all the connections“, right?

**Comment by mitchej123** [comment]
Can't speak for @danbka33  - but the only connections I'm losing are between cable and hatches/machines.  The connections wire to wire are fine.

**Comment by danbka33** [comment]
@Antifluxfield, everything is as @mitchej123 said.

**Comment by Antifluxfield** [comment]
Fine.
