### ISSUE TITLE
Solar panels don't work on cables

### ISSUE THREAD

**Issue by JustOneFeather** [Blood-Asp/GT5-Unofficial#1365]
When placed on machine, it gives energy, but on cables, connectet to any machine, it no longer gives enegry. Bug or feauture? GT 5.09.32-pre-pipes-fix
![2018-01-04_22 41 47](https://user-images.githubusercontent.com/33575695/34581140-771bd1e8-f1a0-11e7-9e73-362a88503017.png)

![2018-01-04_22 34 20](https://user-images.githubusercontent.com/33575695/34580849-75773ef0-f19f-11e7-8db4-aecfdd9e45e8.png)

  #1349

**Comment by SteelGiant87** [comment]
Is that a 1 EU/tick solar panel?

If so, then your panel is generating 1EU every tick, then sending it down that cable and the EU losses of at least 1EU/m are meaning that no energy actually reaches the machine.

You have two options at this point: Either put every solar panel on a transformer so that the energy is stored until it has enough to send it as a bigger packet, or use red alloy wire, which has 0EU/m energy losses (note that red alloy wire can only take 8EU-Voltage)

**Comment by draknyte1** [comment]
Refer the issue to here: https://github.com/Blood-Asp/GT5-Unofficial/pull/1349

**Comment by leagris** [comment]
Solar Panel Fix: https://github.com/Blood-Asp/GT5-Unofficial/pull/1349/commits/5bb0553b8876226004594d0a64242be1b3be3c83

**Comment by JustOneFeather** [comment]
@SteelGiant87 
> Is that a 1 EU/tick solar panel?

Nope, this is 32V panel, as seen on first screenshot on "average input".

@leagris 
Thank you.

**Comment by Blood-Asp** [comment]
Fixed since pre2
