### ISSUE TITLE
Chemistry recipes should require distilled water

### ISSUE THREAD

**Issue by tomasbrod** [Blood-Asp/GT5-Unofficial#1432]
When making delicate chemicals, clean water should be required.

**Comment by JohannesGaessler** [comment]
When I reworked the chemical recipes I chose not to model material purity, so I didn't think of using Distilled Water instead of Water.
I don't think that the recipes should be changed retroactively to require Distilled Water since it would break existing setups for what I perceive as an unimportant change.

How important would you rate requiring Distilled Water?
I would be definitely willing to add a config option for it if there is someone who wants it.

**Comment by leagris** [comment]
It is the kind of change that would need a configuration switch and instead of removing recipes with impure ordinary water, I'd prefer that distilled water bring an advantage with less energy, faster processing or more output.

**Comment by tomasbrod** [comment]
Currently Distilled water is less useful than normal water. I would prefer chemistry recipes to require distilled water. I do not think it would break setups much, because the chemistry is kind of new anyway; and it should be easy to stick distillery in the water line for existing setups.

**Comment by draknyte1** [comment]
What you prefer and what the community wants aren't the same. General consensus from those asked has been negative, so I'll close this. Simply put, Tomas, people aren't fond of changes to chemistry. especially retroactive changes that break existing setups.

**Comment by tomasbrod** [comment]
Can you help me to say my ideas in a way that does not look like I am demanding them? (english) I used conditional mode.
