### ISSUE TITLE
Chemistry complaints

### ISSUE THREAD

**Issue by tomasbrod** [Blood-Asp/GT5-Unofficial#1433]
* [ ] Hydrogen and Chlorine should make hydrogen chloride gas, not acid
* [ ] Phenol from Chlorine, Benzene and NaOH, Na ion is lost in reaction
  * since there already is Chlorobenzene, make it hydrolyse with water, NaOH, and produce Salt water
* [x] Epichlorohydrin from Propanol mixes HOCl and NaOH in one reaction (allyl step)
* [x] Epichlorohydrin from Glycerol is missing NaOH in the hydrolysis
   * I suggest adding dichloropropanol, to be hydrolized with hydroxide to Epichlorohydrin and saltwater
   * To keep complexity down, dichloropropanol could be made directly from propene (HOCl), removing the need for Allyl chloride
* [x] is it intentional that with large chemreactor you can do Ostwald (Nitric) process in one step?
* [ ] add already present catalysts to recipes where number of gui slots allows it (NO, SO3, Methanol)
  * small pile of catalyst can replace the integrated circuit in recipe
* [ ] sulfur dioxide should not be produced in Mixer
* [ ] Hydrogen sulfide should not make acid with water
* [ ] Saltpetre should not be produced by hand (from gases!)

**Comment by JohannesGaessler** [comment]
>Hydrogen and Chlorine should make hydrogen chloride gas, not acid

I decided to only implement either hydrogen chloride or hydrochloric acid since I think implementing both would have been overkill.
Since I got the impression that there are more cases where hydrochloric acid would be used, I chose that material.

>Phenol from Chlorine, Benzene and NaOH, Na ion is lost in reaction

It seems that I've implemented this recipe incorrectly.
The original idea was to give the player the option to add base for a more efficient Phenol recipe (modeled after Dow's process).
However, I forgot to actually add a Salt or Saltwater output which made the recipe objectively worse than the recipe which uses only Water (modeled after Raschig-Hooker process).
I think the best course of action would be to remove the recipe which uses NaOH since a correct implementation would give you very large Fluidstack sizes with no sensible ways to reduce them.
I think that the effort required to compare the two recipes would then be much bigger than the payoff in terms of efficiency you would get from the analysis.

>Epichlorohydrin from Propanol mixes HOCl and NaOH in one reaction (allyl step)

I don't think that this is a problem.
Realistically the Chemical Reactor should be able to do more than just mix all three materials at the same time.
If you have inputs A, B, C it should be able to first use inputs A and B and then add C afterwards.

>Epichlorohydrin from Glycerol is missing NaOH in the hydrolysis

I'm assuming you mean that this recipe would realistically need NaOH.
I chose to do an unrealistic implementation for producing Epichlorohydrin from Glycerol because currently Glycerol is only obtainable as a byproduct from the production of BioDiesel.
I felt that with a complicated recipe the setup would not have been rewarding enough since it's relatively difficult to scale up Glycerol production compared to scaling up Propene production.

>is it intentional that with large chemreactor you can do Ostwald (Nitric) process in one step?

Yes.
Since as a multiblock the LCR is much more expensive than a single-block machine it is able to perform several steps at once for most processing chains.

>add already present catalysts to recipes where number of gui slots allows it (NO, SO3, Methanol) 

I generally chose not to model the use of catalysts for chemical processes.
I think that it would make the game too complicated.

>sulfur dioxide should not be produced in Mixer

I think this recipe is added by GT++.

>Hydrogen sulfide should not make acid with water

Before I changed anything the recipe for Sulfuric Acid used Hydrogen Sulfide and Water.
When I then replaced that recipe with a process via Sulfur Dioxide/Sulfur Trioxide someone who seemed to have better knowledge of chemistry than me assured me that while it's slow and inefficient, it is possible to produce very dilute sulfuric acid by mixing hydrogen sulfide and water.

**Comment by tomasbrod** [comment]
> Before I changed anything the recipe for Sulfuric Acid used Hydrogen Sulfide and Water.
When I then replaced that recipe with a process via Sulfur Dioxide/Sulfur Trioxide someone who seemed to have better knowledge of chemistry than me assured me that while it's slow and inefficient, it is possible to produce very dilute sulfuric acid by mixing hydrogen sulfide and water.

However much I would like to perform an experiment, i lack a lab. Thankfully wikipedia cites that it does indeed produce acidic solution, but the anion is different, it is not Sulfuric acid.

> Since as a multiblock the LCR is much more expensive than a single-block machine it is able to perform several steps at once for most processing chains. Realistically the Chemical Reactor should be able to do more than just mix all three materials at the same time.

If I look at it this way, it makes much more sense. It also has advantage, that one does not have to mess with cells.

Then Allyl chloride is in game only to make it possible to make Epichlorohydrin in small reactor?

* [ ] Also TNT is made from Toluene and Sulfuric, I think for toluene to explode, it needs some nitro-, or at least oxygen.
* [ ] Saltpetre should not be produced by hand (from gases!)
* [ ] Sodium is also lost with Chlorbenzene

What about the Hydrochloric acid without water? Can you add a water to the recipe?

**Comment by tomasbrod** [comment]
With the catalysts, I mean to replace a integrated circuit with a dust pile of the respective catalytic material. I think it would enhance the immersion.

**Comment by JohannesGaessler** [comment]
>However much I would like to perform an experiment, i lack a lab. Thankfully wikipedia cites that it does indeed produce acidic solution, but the anion is different, it is not Sulfuric acid.

The guy who told me it was possible gave me a source though I can't seem to find it again.
I'm not sure anymore about what the source said.
I think it said that the aqeous hydrogen sulfide reacts with impurities in the water and forms sulfate ions.

>Then Allyl chloride is in game only to make it possible to make Epichlorohydrin in small reactor?

Yes.

>Also TNT is made from Toluene and Sulfuric, I think for toluene to explode, it needs some nitro-, or at least oxygen.

That would be correct, TNT should require Nitric Acid.
The recipes are like that for historic reasons.
The old recipes used Sulfuric Acid to produce TNT and Nitration Mixture to produce Industrial TNT.
I think that requiring Nitric Acid for TNT would simply make it too expensive and difficult to produce compared to the benefits you get from it.

>Saltpetre should not be produced by hand (from gases!)

The Chemical Reactor used to have only 1 output slot.
This recipe was then required to produce Saltpeter without losing Cells.
When I gave the Chemical Reactor an extra slot I decided to leave the recipe in because I didn't see a good reason why it should be removed apart from immersion.

>Sodium is also lost with Chlorbenzene

I'm not sure what you're trying to tell me here.
From what I can tell Chlorobenzene is currently only used to produce Phenol.
You have already mentioned this recipe.

>What about the Hydrochloric acid without water? Can you add a water to the recipe?

I think that that would be a poor change.
For a regular Chemical Reactor the logistics of having only 2 inputs is much easier than for having 3 inputs.
I think it would make the recipe unneccessarily annoying.

>With the catalysts, I mean to replace a integrated circuit with a dust pile of the respective catalytic material. I think it would enhance the immersion.

I understand what you mean.
I intentionally did not add catalysts to the recipes because it would require the player to memorize or look up the correct catalyst for each recipe without adding any functional difference.
Also, for most recipes the Programmed Circuit is important.
It determines how the products should be canned and whether byproducts like Water should be voided.

**Comment by draknyte1** [comment]
I think all the points mentioned above are nitpicks are Johannes consistency across chemistry. Nothing worth actually changing though, or you'll piss off Antillar. 

While improvements are nice, this isn't real life and compromises are made for gameplay value. We've got people documenting this mod and constant changes to chemistry has become a pain in their back, along with the annoyance it causes to players. 

While I don't think this is any more than a discussion, I'll reopen it if any useful content suggestions come out of it.

**Comment by tomasbrod** [comment]
I am understand the gameplay complexity concerns. When thinking about these "complaints" i always try to not introduce new "useless" items or steps.
Yes, this is a discussion, I am not commanding. I think i should close the other old issue of mine as well. Thankfully this is open source and I can experiment how I want. I will look at HTNH fork, to avoid some(?) duplication.
