### ISSUE TITLE
No ore processing recipe for Realgar Ore

### ISSUE THREAD

**Issue by PaladinOne** [Blood-Asp/GT5-Unofficial#158]
Per Fabrica Ad Astra: Geologica adds many, many ores. Most of those ores have processing recipes for them. However, Realgar Ore (Arsenic) (OD: oreRealgar) does not have recipes.

Realgar's chemical formula is As4S4.

**Comment by Blood-Asp** [comment]
I'm not perfectly sure without looking, but most of the compatibility work between PFAA ores and GT was done on PFAA side if i remember right.

**Comment by PaladinOne** [comment]
IIRC the PFAA compatibility comes in how it registers its things in the Ore Dictionary. In this case I think it's more like an "unknown material"-type GT error, except that my startup log doesn't show any "unknown material" or "unknown thingy" messages.

**Comment by lawremi** [comment]
Although there is no evidence in github, I've actually been pushing really hard lately on integration of PFAA with other mods, with a special eye to Gregtech (5).  It's sort of a weird situation, since Gregtech has "adopted" all of the PFAA materials, so there will likely be some recipe changes, not just additions. I've been studying Gregtech so as not to break the gameplay. 

If Blood-Asp is open to it, I can contribute support (via PR) for realgar and other barely-supported PFAA materials.

**Comment by Blood-Asp** [comment]
Everyone is free to make pull requests. Stuff like bugfixes or enanced mod compatibility are sure to be accepted as long they are not broken or somehow breaking balance.

PRs adding new stuff are also fine. In case i do not like them, hiding them behind a config is enough for me to accept it.

Also be warned, the "Materials" Enum has reached the max size java allows. Adding new materials is now only possible by deleting materials not used in modded minecraft anymore.

**Comment by lawremi** [comment]
Sounds good. Why not add a second enum and have the original and new enum implement the same interface? That may be the only way going forward. The interface would also allow other mods to define their own materials.

**Comment by Blood-Asp** [comment]
Adding an interface and multiple enums would mean massive changes and i will not do that. Main reason: Greg did all that in GT6! Other mods can add New or change existing Materials without problems. Allmost all support for other mods got a lot better. Now GT6 must only get enough content that switching over is fine.
