### ISSUE TITLE
Weird Fusion Computer EU storage

### ISSUE THREAD

**Issue by AiwendilCiunio** [Blood-Asp/GT5-Unofficial#161]
<a href="http://imgur.com/XhrmmXy"><img src="http://i.imgur.com/XhrmmXy.png" title="source: imgur.com" /></a>

4 LuV Energy hatches (10m each), why is it 512 EU short of required 40 million? It's kinda annoying and it won't start.

**Comment by Blood-Asp** [comment]
It can only accept full EU packs. So if you would input at 512 EU/t, it would fill up the remaining one. All other GT machines also do this, you just do not see it as there is no visible EU number. Charging batteries works in another way because of missing transfer distance.

Even if you had exactly 40mio EU stored to start a 40mio reaction, it would start up and instantly stop since there is no EU left to keep it running. So you allways must have a bigger storage anyways.
