### ISSUE TITLE
Plasma Turbine output

### ISSUE THREAD

**Issue by AiwendilCiunio** [Blood-Asp/GT5-Unofficial#162]
Currently plasma turbine doesn't output anything, which doesn't really make sense. Helium plasma should become helium, oxygen plasma oxygen etc.

**Comment by pyure** [comment]
Aiwen, have you done research on this?  

The whole notion of a "plasma turbine" itself is probably a bit odd, so trying to determine a sensible byproduct (such as helium) and in what quantity would likely be difficult. 

But if there's a sensible byproduct based on actual research, adding it in is simple.

(tl/dr: I don't wanna code in 1:1 plasma:helium just cuz it sounds cool)

**Comment by AiwendilCiunio** [comment]
No I haven't, actually. But something should come out - plasma is matter after all. I'm not sure what happens to it when it's cooled down - does it break into its components or does it become a normal state of the element (i.e. helium plasma -> helium gas).

We would have to ask some physicist I'm afraid :)

**Comment by AiwendilCiunio** [comment]
I found this though:
http://www.crossfirefusion.com/spacedrive-electric-propulsion/phase-shift-plasma-turbine.html
It's difficult to understand for me though, and I don't wanna spend an hour with a translator :)

**Comment by pyure** [comment]
https://www.iter.org/sci/fusionfuels

Last paragraph suggests that helium is a legitimate byproduct of a helium fusion reaction.  Next, just need to figure out what proportion is returned as inert helium as opposed to converted into energy.

**Comment by pyure** [comment]
I can't seem to find any numbers on this.  The prevailing theme is "we're not certain because we haven't done it in production yet."

Two questions:
1) Do all our plasma types (Oxygen, Helium, etc) have a valid non-plasma-form we can use as a byproduct?
2) Any issues with us arbitrarily picking a percentage...say 50%...that would be ejected as a byproduct?

So if you react 50mb of A with 50mb of B, you'd get (1) Energy + (49)AbstractedJunkAshStuffWeDontDealWith + (50)Helium = (100 total mb)

Taking some liberties with numbers here:  I suspect more helium than this is generated.  But GamePlayBalanceFirst, and 50% is a nice round number

Also, I wonder why we don't use plasma to generate power via steam.  It seems to me we should be feeding plasma into the LHE or an equivalent instead of into a turbine directly.

**Comment by Blood-Asp** [comment]
The only reason for far that large plasma generators have no cold fluid output, is that it never had one, back in GT4.

As long it is made sure that there is no balancing issue, it is fine to me adding something like this.

Turning plasma into steam would be realistic, but the amount of steam per tick is just too large. So large that it would be silly. Adding a "ultra superheated steam" or whatever would also be a bit silly, so i vote for staying with direct plasma -> energy. If there was a change, that would be that the fusion reactor itself should output heat and not plasma.

**Comment by pyure** [comment]
Yeah, you hit the exact same logistical problem I did: too much steam.

The other option was to to let a very tiny amount of plasma generate "not silly quantities" of steam.  So you'd need many LHEs/Turbines for a single Fusion reactor.

**Comment by Blood-Asp** [comment]
That would result in machine spam. Even more bad.

**Comment by pyure** [comment]
A line of LHEs and Turbines looks awesome, not bad.  Get with the program.

(I'm actually going to give this more thought.  I don't see any idea solutions, but we already have all the infrastructure in place to make power-from-steam work here if we really want to)

**Comment by ShelfOwl** [comment]
Then my suggestion: Plasma can heat only IC2Coolant in LHE.

And if you add some functions, please make consider about Iron and Nickel Plasma.
IMO producing Helium, Nitrogen or Oxygen as a byproduct is good, but "Produces not only energy but also metals" sounds bit overpowered.

**Comment by DarknessShadow** [comment]
>That would result in machine spam. Even more bad.

.
>A line of LHEs and Turbines looks awesome, not bad. Get with the program.

Looking from the gameplay aspect it would be good if the fusion reactor required a big infrastructure to get the energy out of plasma but from the performance perspective we shouldn't force people to spam machines.

If you want to solve it without machine spam then make an upgraded large steam turbine which uses 10-100 times more steam.
>Then my suggestion: Plasma can heat only IC2Coolant in LHE.

Plasma in LHE -> IC2 hot coolant
IC2 hot coolant in LHE -> (superheated) steam
Running that twice through the same machines doesnt really make sense.

I think it should only be plasma in LHE -> superheated steam
>And if you add some functions, please make consider about Iron and Nickel Plasma.
IMO producing Helium, Nitrogen or Oxygen as a byproduct is good, but "Produces not only energy but also metals" sounds bit overpowered.

I don't think its overpowered that it also gives iron / nickel as a byproduct because to get that you need Mark 3 Fusion and by the time you can do that you don't really care about those tiny amount of extra iron / nickel from the fusion reactor especially when we compare it to a quarry.
>1) Do all our plasma types (Oxygen, Helium, etc) have a valid non-plasma-form we can use as a byproduct?

yes

**Comment by leagris** [comment]
I think there is already and significantly enough machine spam involved in processing fusion materials.
And there is already no sane logistic solution to distribute energy on long distance and inter-dimensionally.
So, forcing more machines logistics on energy generator side is a total non-sense.
High energy fuels are the only available mean of transporting and distributing high power unless you distribute or transport batteries.

**Comment by mura3277** [comment]
Why don't we have Superheated Steam have it's own turbine fuel value?

And to solve the issue of too much steam, you could figure out a balanced superheated steam output from the Large heat exchanger (When you input plasma) and just reduce it by a factor of 2 or 4. 

Now all you have to do is adjust for this by increasing how much power superheated steam makes.

Also I know this is an old issue, but it is a really good and interesting idea and I wanted to revive it a little :p

Thanks.

**Comment by perkinslr** [comment]
Okay, so I have implemented plasmas outputting their associated liquid type in a generic fashion.  If there is any interest, I can post a patch-file for the changes needed.  Basically, it uses the fluid name of the input, calculates the likely fluid output name and sees if it exists, if so, it outputs, otherwise, it skips outputting.  All plasmas start with 'plasma.', the base type is either just the raw name, or 'molten.' + the raw name.  As for the amount to output, it's one to one.  I'm a chemist by training, so I apologize if the explanation of why is not perfectly easy to follow.  If anything doesn't make sense, just ask.  

Pretty much everything in GT assumes stoichiometric ratios of inputs (4 Hydrogen to 1 Carbon for making or breaking methane) rather than mass-equivalent or volume-equivalent ratios.  Note that this is not perfectly consistently followed, if you take that same 1 carbon from splitting methane and run it through a fluid extractor, you get 144L of carbon, compared to 4kL of oxygen.  On the other hand, that is mostly acceptable since it's liquid carbon vs gaseous hydrogen (it would even be the perfectly correct volume ratio for some ambient pressure).  So, consider the inputs to the fusion reaction.  125 <sup>12</sup>C<sub>l</sub> + 125 <sup>3</sup>He<sub>g</sub> -> 125 <sup>16</sup>O<sup>+8</sup><sub>g</sub>.  (Note that it should probably be using <sup>4</sup>He as input, since otherwise the mass-balance is off, but that's a different issue).  The turbine is then facilitating the same reaction as the freezer O<sup>8+</sup><sub>g</sub> -> O<sub>g</sub>.  As with other general GT reactions, this should be stoichiometric, so 1 input gives 1 output.  The other possible output would be 0.5, if we assume the output form is O<sub>2</sub>, except that then splitting methane should only produce 2 hydrogen, since it similarly will form as H<sub>2</sub>.  

On the general discussion about plasma turbines and how to overhaul the fusion reactor:  
There seems to be a bit of confusion about what plasma is and what happens to it when it cools.  Plasma is an atomized element without any electrons.  Without electrons, atoms cannot bond to each other, so diatomics and other compounds will split apart.  The easiest way to generate plasma is simply to heat it up, thereby providing enough thermal energy to encourage the electrons to leave.  Note that if you let it cool under the proper conditions (no free electrons for it to grab), you'll still have plasma, just at a lower temperature.  Of course, if you let it cool without insulating it, it will pull electrons from wherever it can, inducing a positive charge in whatever donated the electrons, which you can use to generate a voltage differential (which can cause current to flow, i. e. electricity generation).  You could also use it to cause a positive charge on an arm of a turbine, which would cause the turbine to rotate if it's in the presence of a proper magnetic field.  I'm not sure if this would be more efficient than simply harnessing the voltage differential the plasma itself will cause.  I do know it wouldn't work with a neutronium turbine, since it has no electrons to donate.  

To figure out the amount of energy available in plasma, neglecting the heat, since it's fairly small by comparison.  The amount of energy required to drive off an electron is called the ionization energy.  Of course, elements with more than one electron have multiple ionization energies and the energy required to form plasma is roughly equal to the sum of the ionization energies.  For O<sup>8+</sup>, you're talking 197,193 kJ/mol (1 mol is 16 grams of oxygen).  Obviously, the conversion to EU is nebulous, but it gives some idea of the relative values (H<sup>+</sup> is 1350 kJ/mol (1 mol is 1 gram of hydrogen)).  

The idea of outputting steam or HU or IC2 hot coolant has already been mentioned, but I think either one would be a poor choice.  Obviously, the fusion reactor is generating plasma by heating up, so the heat should factor into it, but water->steam or cold ic2 coolant -> hot coolant aren't going to be sufficient.  Compared to the energy available in the plasma (12324 kJ/gram is a lot!!! lithium ion batteries provide 0.46 kJ/gram), the energy released by the fusion itself is enormous: for deuterium to helium, it's 576,035,099 kJ / gram, 46 thousand times the energy available in oxygen plasma.  After starting the fusion, none of the energy the reactor is spending is propagating the reaction, it's all spent on containing it so it doesn't explode (on that note, input power failures should probably be catastrophic).  Water is simply not sufficient for cooling at these kinds of power output.  It has a heat of fusion (energy to go from liquid to gas) of 333 kJ/kg.  Instead, it should be sucking in some additional fluid and turning it into plasma (oxygen would get you 12,324,000 kJ/kg of cooling 37,000 times the cooling power of water->steam).  

Obviously, there's no need to get the values close to reality, using values to make math easy and not unbalance the mod makes sense, but this gives some idea of the scale involved in fusion.  What I would envision, since it already handles multiple input and output hatches would be this.  The fusion reactor itself doesn't initialize any reactions, it sucks power to maintain a containment field.  The power required to contain the reaction depends on what reaction is taking place and how hot the reactor is.  The reactor takes plasma as input, generated via a secondary machine.  It causes the fluid to react with the paired input (top to bottom), increasing the temperature of the reactor in the case of exothermic reactions, decreasing the temperature in the case of endothermic reactions.  At the same time, non-plasma inputs turn into plasma as output, which is the primary energy output for exothermic operation.  

Anyway, that's my thoughts on how to move the fusion reactor along, like I said before, if anyone's interested in a patch I'll post one, and if there are questions about how fusion reactors could work, I'm happy to discuss that too.
