### ISSUE TITLE
Cannot break (my own) machines with lock upgrade

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#166]
I've given the lock upgrade to almost all machines and now I cannot break them anymore (with the wrench) rightclick with wrench and opening gui (+ processing) still works normally.
Strangely I can break machines right after I've given them the lock upgrade but after some time it doesn't work anymore.
I tested it with a Naquadah Alloy and a Palladium Wrench.
https://www.youtube.com/watch?v=A5eeyxwfwJo&feature=youtu.be

gregtech_1.7.10-5.08.27

**Comment by DarknessShadow** [comment]
Is this fixed, intended or am I doing something wrong?

**Comment by Blood-Asp** [comment]
Found a second issue with the lock upgrade due to client/server sync.

LockUpgrade got synced, owner name not.

Quick fix for that in 5.08.29: lock upgrade also does not get synced. The result: It looks like the machine does get mined to players not allowed to mine them, but it does not get dropped and on next server/client sync the machine reappears. Not a nice fix, but fixing it for real is quite complicated. Simply sending the player name with every GT TE (that includes all GT ores) would create massive traffic for servers.

**Comment by PaladinOne** [comment]
Could an optional (i.e. return bit '0' if unowned) playername parameter be created on GT MTE classes that aren't the ore block class?

**Comment by Blood-Asp** [comment]
Whatever i do, i must add new sync packs. Thats quite a lot of work to make sure it does work. Especially because testing server/client stuff is complex. So a currently only visual bug has low priority.
