### ISSUE TITLE
Reactor items/components

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#187]
From an IC2 update 2.2.763 to 2.2.770 there was some change which broke the recipe for certain heating components of nuclear reactors.

With IC2 763 the thick neutron reflector used to require beryllium, now it uses 5 copper. As well the iridium neutron reflector doesn't seem craftable

**Comment by bear989** [comment]
after builg #773 the Ic2 heat vents now are 4315:1, the GT equivalent doesn't and wont work in advanced heat vents and others

**Comment by axlegear** [comment]
This one's a bad one, making IC2 reactors almost unuseable.

**Comment by Blood-Asp** [comment]
Fixed the reflectors. What do you mean with Heat Vents? GT does nowere touch them.
In case you had them in autocrafting before the update, you simply have to remake all programmed recipes using them, but that is not my fault.

**Comment by axlegear** [comment]
This is not due to autocrafting.  Bear knows the problem in detail as he made a minetweaker script to fix it.  I can only explain it as such:
When making an Advanced Heat Vent using the diamond, 2 heat vent, 6 iron bars, it will not accept the heat vents.  Ditto for the NaK cells, component coolers, etc.
It appears to be due to the recipe asking for heat vents #4315 and not accepting the actual crafted heat vents #4315:1  (or I may have that reversed) along with several other nuclear components.  I'll ask Bear to attempt to give better details as he understands the problem more intimately.

**Comment by bear989** [comment]
the updates to IC2 exp that change the reactor components to have a damage value when crafted messed with recipe for advanced heat vents, this is the MT for fixing

recipes.addShaped(<IC2:reactorVentDiamond:1>, [[<minecraft:iron_bars>, <IC2:reactorVent>, <minecraft:iron_bars>], [<minecraft:iron_bars>, <minecraft:diamond>, <minecraft:iron_bars>], [<minecraft:iron_bars>, <IC2:reactorVent>, <minecraft:iron_bars>]]);

Also the coolest cells received the same change

recipes.addShaped(<gregtech:gt.60k_NaK_Coolantcell>, [[<ore:plateTin>, <ore:dustSodium>, <ore:plateTin>], [<ore:dustPotassium>, <IC2:reactorCoolantSimple:1>, <ore:dustPotassium>], [<ore:plateTin>, <ore:dustSodium>, <ore:plateTin>]]);

hope this helps

**Comment by Blood-Asp** [comment]
IC2 did changes there, but there is nothing in GT that touches the heat vents. Maybe you had old allready crafted ones stocked? There is an 1x1 crafting recipe for all heat vents. That should fix issues.

The coolant cells and neutron reflectors are all GT has and i did fix them in dev. Tried crafting them from raw materials up and everthing worked.

**Comment by axlegear** [comment]
Are you sure?  Because I distinctly remember a 4 iron bar, 4 aluminium plate recipe for heat vents that is exclusive to GT, and it's the recipe I use (rather than the motor based one)
