### ISSUE TITLE
EU/flow meter

### ISSUE THREAD

**Issue by willis936** [Blood-Asp/GT5-Unofficial#189]
Suggestion to add functionality to the portable scanner or to make a dedicated scanner that observes statistics of GT tile entities so you can see fluid and EU in/out of pipes, cables, and machines.  This would make debugging builds so much easier.  For EU stats on the voltage observed (assuming it doesn't change) and total EU/t (max, min, and average).  Fluid should be in L/t even though it's typically in L/s so that finer granularity is shown to the user.

**Comment by Blood-Asp** [comment]
Creating a tool to observe the "per Tick average over time" would be quite a lot of work. Especially to do that without creating a huge amount of lag.

**Comment by pyure** [comment]
Yep, I've looked into this (a few times) and I always run into problems because of greg's separation of client/server data.

**Comment by Blood-Asp** [comment]
That client/server communication is not a problem. Just look at how the allready existing scanner does it. Then everything else to do is server side.

The problem ist, to be able to make average calculations, every transfer in every block, cable and pipe must be saved and ready to be called on click. That would create massive lag.

So that does not happen, the way would be to start logging on first click and show the results on a second click. Possible, but it would be at last 5 classes that need 50-100 lines of extra code to make it work. And this code would be directly in the core of all machines and cables. A place i really dislike to even touch.

**Comment by pyure** [comment]
Its funny, I don't see problems with the calculations lag (you just make sure it doesn't cycle every tick if necessary), but I can't figure out the server/client stuff to save my life :)

**Comment by SapientMC** [comment]
May be simple model could be used: just after click and for next 3 (or 5) seconds it calculates data and displays it after.

**Comment by Muramasa-** [comment]
As SapientMC said, recreating the old 1.4.7(I think) IC2 EU-Reader might be the best way to go.

It just recorded the average eu/t for the duration between your two clicks.

**Comment by perkinslr** [comment]
Zetta Industries has an RF meter block that works quite well.  It accepts power on only one side, and basically passes all add-power calls through to the block on the opposite side, then displays the amount of power it was last offered.  It creates a break in the network, so it does slightly increase the server load (a little less than adding an energy cell at the same location).  It should be fairly simple to do something similar specifically for battery buffers and transformers.  It wouldn't tell you how much power is traversing an arbitrary point, but it also wouldn't increase the server load appreciably, and could just dump the info to the tricorder.

**Comment by Blood-Asp** [comment]
Added to idea collection
