### ISSUE TITLE
Client (almost) crashed!

### ISSUE THREAD

**Issue by DeckerCHAN** [Blood-Asp/GT5-Unofficial#209]
Using the latest version of GTU(5.08.30). 
After updated form 08.28:
  (1) Blast furnace start produce infinite productions(for me, is tungsten ingot). 
  (2)Type filter is done. It does not work any more. GUI crashed as well
![image](https://cloud.githubusercontent.com/assets/1845937/10280908/47315866-6bbc-11e5-9978-f214a9e028e2.png)
  (3) Console start to produce error message below:
http://pastebin.com/jTjX6qmt

**Comment by Blood-Asp** [comment]
This report is so long, it crashed my mobile...
Please attach them as text file or link to pastebin.
About the endless ingot production, please redownload GT. I reuploaded a quickfix soon after.

**Comment by JasonMcRay** [comment]
@Blood-Asp I am bored at work so: http://pastebin.com/jTjX6qmt for convenience ;)

**Comment by Blood-Asp** [comment]
As i see it, the issue is trying to render a modified mobspawner.  It just randomly happend inside a GT Filter...
So should that allways happen, try to remove the mods that somehow change mobspawners(or add mobs that get added to mobspawners). Maybe even what mob exactly is crashing.
There is still a change that GT is involved in that crash so i will leave this issue open for now, but the crash report alone is not enough for me to find the reason.

**Comment by Blood-Asp** [comment]
No more info = close.
