### ISSUE TITLE
Granite Bricks not "not-allowing" monster spawns

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#222]
Tooltip says that Red Granite Bricks are not allowing mobs to spawn, but everytime I get back on my server I see Zombie Pigmans inside my base.

I have a nether portal and in the Nether I have build fully granite encased tunnel from portal to my lava pump. There is no spot with other block than Red Granite Brick, but still getting the Zombie Pigmans to spawn.

**Comment by Blood-Asp** [comment]
Zombie pigman do not cross the portal, they spawn close to the portal. So even if the nether side is save, there will still pigman appear in your overworld portal. To stop that, you would have to prevent spawning also on the overworld side. That is at last how i know the vanilla mechanic. Maybe instead of Granite use an "monster repellator" on your overworld side? An unpowered MV close to your portal should be enough.

**Comment by JasonMcRay** [comment]
Hmm.. well.. I have a Magnum Torch covering my whole base (if someone did not broke it)

**Comment by Blood-Asp** [comment]
Yes, maybe pigman do not count as hostile. The monster reprellator does the same as the magnum torch, so it will not be better in that case. It might also be, that the obsidian of the portal itself can be used as spawn area.
