### ISSUE TITLE
Tin Ore not spawing

### ISSUE THREAD

**Issue by nintendow131** [Blood-Asp/GT5-Unofficial#243]
Tin Ore (Casserite) doesn't seem to spawn at all, although all other Ores spawn like they should. This is a Problem, because you need about 87 Tin for a BBF.

**Comment by Blood-Asp** [comment]
Tin veins are really difficult to find. Only spawn high and have a badly visible color, but they do spawn. You can enable the "debug1" config, then the console outputs what orevein just has been generated. Only if there was after 100+ veins no tin vein, i will accept it as an real "not spawning".

**Comment by nintendow131** [comment]
I have the minimalist Texture Pack, so would see Tin ore easily. I've checked the Landscape with the X-Ray mod multipe times and the only Ore veins that spawn relativly high are Magnetite/Vanadium Magnetite/Gold veins.

**Comment by joflashstudios** [comment]
Tin veins are, as Blood said, really difficult to find. I've been playing with the highlands pack, and even with lots of giant stone mountains, it's quite rare. It seems like you're much more likely to get gold/magnetite, coal, or bauxite/aluminum. And this isn't due to visibility - without mipmapping and with the Minimalist textures, they're quite visible from a distance. They're just very rare. However, it DOES spawn.

**Comment by Dream-Master** [comment]
Gregtech have a config file where you can change existing ore mixes or create new ones. I am using 15 new ore mixes in my pack and it is possible get more than this.
(Worldgen.cfg in the Gt config folder)
To looking for veins using coch core in your pack and using the "clearblocks" command
/cofh clearblocks YourMCName 100 100 100 dirt (for dirt)
/cofh clearblocks YourMCName 100 100 100 stone (for stone)
