### ISSUE TITLE
Naquadah Cells

### ISSUE THREAD

**Issue by dohvakin96** [Blood-Asp/GT5-Unofficial#265]
Naquadah and enriched Naquadah cells allow producing Nq or Nq+ Ingots without a blast furnace. Simply fill Nq or Nq+ dust in cells, then put in the arc furnace, saving over 700.000  EU and 300 seconds of producing time. Is that intended?

**Comment by ShawnBuckley** [comment]
That looks wrong.  Which version are you running?

**Comment by dohvakin96** [comment]
5.09.09 but I noticed that bug some time ago (I think it was in 5.7.8 or something like that), but forgot to report it.

**Comment by Blood-Asp** [comment]
Fixed in experimental with https://github.com/Blood-Asp/GT5-Unofficial/commit/a2ad9c9e8359f693f20bc0cc880fbf2bf2785868 now, how to apply that on the main branch? @ShawnBuckley

**Comment by ShawnBuckley** [comment]
@Blood-Asp A cherry-pick would be best since we don't want to merge the entire experimental branch back into master.  I just picked it and pushed it.  The version in the Materials enum got bumped since it was a part of the experimental branch, we might want to think of a different strategy for checking versions if we are going to be maintaining branches in this fashion.
