### ISSUE TITLE
Extra Cells shows fluids with wrong textures

### ISSUE THREAD

**Issue by dohvakin96** [Blood-Asp/GT5-Unofficial#289]
Extra cells fluid terminal shows all "molten" things (molten metals, molten rubber, etc.) with the same, white texture (not the "missing texture" texture). Is it extra cells fault or can you do something about it?

**Comment by SapientMC** [comment]
There are even more bug
https://github.com/ExtraCells/ExtraCells2/issues/313

**Comment by Blood-Asp** [comment]
GTs "molten" fluids are autogenerated. They all use the same white texture with a color modulation. I can't say for sure if EC needs special support for that, or is simply wrongly implemented. But since all other mods that show the molten fluids visible in world show it correctly, it should be on EC side to fix.
