### ISSUE TITLE
Idea: Tier 2 Processing Array

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#314]
BloodAsp, is it possible to add Ties 2 ProcArray, made from for example Europium or Fusion casings and with ability to contain up to 32 (or 64) machines?

**Comment by axlegear** [comment]
Why not just build... two PAs?

**Comment by antkatcin** [comment]
Because this guy is awesome youtube streamer who already has something like a dozen of PAs, and he just doesn't want to add a few more dozens :)

**Comment by SapientMC** [comment]
axlegear, I already have 20 of them (for D+T production) and its something like 31 more needed (for infinite Nitrogen Plasma production).

**Comment by Blood-Asp** [comment]
Personally i want to aim next changes to need less machines so that bigger PAs is only the last way out.

**Comment by leagris** [comment]
#### I'd suggest higher density processing arrays while being more costly to build (Require EV age); Should have a significant performance gain by either:
- Using 1/4 of internal machines number energy. Example: 64 Machines consuming that of 16.
or
- Removing over-clocked recipes EU penalty in dense PA. (**preferred outcome**)

#### Economy of scale:
- Bigger machines do more work for less energy/less cost per operation.

#### In counter-part.
Dense PA should:
- Only accept an exact multiple of 4 machines.
- Need number of machines amperes input: (64 machines need 64 Ampere)
- Require at least EV machines (Building dense PA should require only materials available with EV age.
#### Goals
→ This all should encourage use of higher tier machines. Higher tier power generators, 8x cables and 16 wires that are only recipes components for now.

**Comment by DarknessShadow** [comment]
"Dense" processing arrays would be nice to have some really big, high end processing systems :)
>Only accept an exact multiple of 4 machines.

I don't understand why?
>Need number of machines amperes input: (64 machines need 64 Ampere)

That would be good so you dont have 16 lv machine and simply connect hv 1 amp.
>Require at least EV machines (Building dense PA should require only materials available with EV age.

I think the "dense" processing array should require fusion.

**Comment by leagris** [comment]
> >  Only accept an exact multiple of 4 machines.
> I don't understand why?
→ Consequently enforce multiples of 4Amp energy input.

> >  Require at least EV machines (Building dense PA should require only materials available with EV age.
> I think the "dense" processing array should require fusion.
Fusion already encourage use of Processing Arrays.
Forced use of EV age as minimal and given the high Amperes requirements, it means you already need beefy energy supply and transport infrastructure. You can not do that easily with single-block generators. It means you are already at least equipped with Nuclear reactor or large turbines of some kind.

Maybe some advanced highest tier of processing arrays could incorporate some computing logic and handle a whole chain of heterogeneous machines where you could have ores, fluids on input and all processed sub-products at the output dusts and fluids.
These could act as compact templates for ore processing chains.
Thesse would be part of mid-end game where you can be motivated to modernise your existing infrastructure to something more efficient.
→ Server admins would always welcome occasions of player bases consuming less CPU cycles.
→ Players would have something to do and motives to invest more in their existing infrastructure.
Instead of deploying more of the same old starter machines.

**Comment by SapientMC** [comment]
> Personally i want to aim next changes to need less machines so that bigger PAs is only the last way out.
Do you plan this changes in 5.08 too?

**Comment by Blood-Asp** [comment]
No, 5.08 will not get changes like this anymore. If i will do even anything like this is not for sure.

**Comment by Blood-Asp** [comment]
Hmm, why did i not close this? I allready said there will be no PA MK2...
