### ISSUE TITLE
Process items over a stack in Processing Array

### ISSUE THREAD

**Issue by siriulx** [Blood-Asp/GT5-Unofficial#320]
If I want electrolyze obsidian dust in a Processing Array, It should process 12x16 obsidian dust once. But the PA can't process things over one stack. It only process 12x5 obsidian dust once. I don't know if it is just designed as this.

**Comment by Blood-Asp** [comment]
Sadly code wise not a simple change. Also border cases that are not the original intention behind the PA. So that function will not be added by me for now.

**Comment by Timeslice42** [comment]
I would argue that this is not a corner case issue, but in fact a primary use case of the machine. Bulk processing is literally what the processing array is all about. I also suspect that this issue would address some of the other problems with multi-block processing, such as not pulling from or inserting to multiple slots at once. For example, try processing three stacks of stone dust and a stack of clay in a mixer, it won't do the last oepration; or try processing a stack of iron ore and a stack of calcite in an EBF, the last ingot will be destroyed because it cannot find a single slot with enough open space, despite there being enough room total.
