### ISSUE TITLE
Pipes cause cables to look weird

### ISSUE THREAD

**Issue by retep998** [Blood-Asp/GT5-Unofficial#346]
![](http://i.imgur.com/OOzov81.png)

GT 5.09.13 with Forge 1517

**Comment by retep998** [comment]
Further testing reveals its not just a rendering bug. No energy goes across the bugged cable.

**Comment by Blood-Asp** [comment]
can not replicate this behavior. Also can't find anything that might be the reason in the code. Does this happen with all cables/pipes? Did you try it with a pure GT setup?

**Comment by doushio9967** [comment]
I've seen reports of that since the early versions of 5.09, but never tried to replicate it myself.
Any TE adjacent to energy cables (including things like chests) will cause them to disconnect.
Adding paper or some other cover inbetween the pipe and the cable should atleast stop them from interfering with eachother and the cable to not disconnect like that, from what I've seen.

First report I saw of it was on a pure Forge/IC2/GT setup (not even NEI was in), so I doubt it's some obscure mod that is causing it.

**Comment by doushio9967** [comment]
Hm, actually, on further testing that was pretty easy to trigger..

![2015-12-07_22 36 02](https://cloud.githubusercontent.com/assets/6629858/11640653/fdee6320-9d33-11e5-865c-7f8643e57d58.png)

**Comment by Blood-Asp** [comment]
So it needs the combination of no RF api and it enabled in the config? Well, that more or less sounds like wrongly set config... but i should add an check for the api present and it disabling automaticly the support for it.

**Comment by doushio9967** [comment]
Yeah, OutputRF is on by default since 5.09. But I guess not many people play without any RF mods whatsoever, hence why there's been so few reports.

Oh, and as the screenshot shows, the cables don't get split up like that in the west and east directions, for whatever reason..

**Comment by Blood-Asp** [comment]
What basicly happens is, that the cable tries to check of there is an RF cable next to it, but since there is not RF api, it crashes while checking. That crash is catched by GT so minecraft does not fully crash, but still the check for possible connections terminates and the cables do not connect.

**Comment by PaladinOne** [comment]
Thank you GregTech for try/catching almost literally everything...
