### ISSUE TITLE
Nitric acid has no texture

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#350]
![2015-12-07_16 19 12](https://cloud.githubusercontent.com/assets/8433695/11640004/48f51af2-9cfe-11e5-8594-379144dcef06.png)

**Comment by bear989** [comment]
also it isnt flowing out with auto output fluids selected, the next machines input tank is empty,

![2015-12-07_16 21 31](https://cloud.githubusercontent.com/assets/8433695/11640066/9b320604-9cfe-11e5-83f5-6e0d26492634.png)

**Comment by Blood-Asp** [comment]
Is this with most recent IHL version, or the one before removal of it's platinum group processing? In my testworld the swich worked fine with most recent IHL version.
But well, i know what the issue is. The load order of the fluids changed and forge is a bit buggy here. Had the same issue with Galacticraft a while back.
It should be fixable by me by moving the fluid registration in GT from preload to load phase. You should also be able to fix it, by using NBTEdit. Open the level.dat file with it go in the forge folder and remove the buggy fluids from the fluid list. After a restart, forge rebuilds it's fluid list correctly.

**Comment by bear989** [comment]
yes this is most updated IHL and GT5u
