### ISSUE TITLE
Strange ore vein size calculation

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#383]
Given vein configuration has `I:Size_16=16`:
- How can this Pitchblende Ore vein spread 24 blocks West↔Est and 46 blocks North↔South?

![2015-12-28_00 12 07](https://cloud.githubusercontent.com/assets/1111474/12012498/878d7476-acf8-11e5-8bd7-e7888e79e39f.png)

#### `WorldGeneration.cfg` for Pitchblende Ore
```Zephir
pitchblende {
    B:Asteroid_true=true
    I:Density_3=3
    B:EndAsteroid_false=false
    B:EndAsteroid_true=true
    B:Mars_true=true
    I:MaxHeight_40=40
    I:MinHeight_10=10
    B:Moon_true=true
    B:Nether_false=false
    I:OrePrimaryLayer_873=873
    I:OreSecondaryLayer_873=873
    I:OreSporadiclyInbetween_922=922
    I:OreSporadiclyInbetween_98=98
    I:OreSporaticlyAround_922=922
    B:Overworld_true=true
    I:RandomWeight_40=40
    I:Size_16=16
    B:TheEnd_false=false
}

```

**Comment by Blood-Asp** [comment]
Size means the following: Min size (0) is always 16x16.
Then it get's stretched in each direction by random 0 - size. So a size 16 vein can be from 16x16 up to 48x48 big. a size 24 vein could be up to 64x64, but still min size is always 16x16. Because of that it is also not always the center chunk of the vein the actual center cunk of the generation.

ftb.gamepedia.com/GregTech_5/Mining_and_Processing The wiki as some more infos. (But also soo much text that it might be missed)

**Comment by leagris** [comment]
Ah, thank you, now I fully understand how that is calculated.
