### ISSUE TITLE
Dye Sprays not working as dyes

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#400]
Originally (in GT4) the dye spray cans were also usable as dyes in crafting recipes, and it would consume some of the charges to do so (four times as much as spraying a block, IIRC). It would be really nice if they could do so again.

**Comment by leagris** [comment]
I tried to add Dye Spray to oreDictionary and hearted unexpected results.
- Spray get consumed entirely and an empty spray can is returned to inventory instead of consume 1/512 of uses.
- Found out Dye Sprays use different meta if just crafted or used
- Crafted Dyes Spray have no int GT.RemainingPaint NBT tag
- If you click a newly crafted Dye Spray on an non-dyeable block, it becomes a used Dye Spray with 512 remaining uses.
- A Dye Spray is crafted using 2304l of Chemical Dye in a Gregtech Fluid Canner, but 1000l only with a Forestry Bottler
- Dying a blockWool in a Chemical Bath consume 72l of Chemical Dye. You would dye only 32 blockWool with 2304l of Dye that way, whereas 512 blocks if used in-world with a Dye Spray. To be fair, a Chemical Bath should dye a block with only 4l of dye. That would make in-world Spray Dying consume 4.5l of dye per use (thus 512 uses)

**Comment by Blood-Asp** [comment]
Added to idea collection
