### ISSUE TITLE
Cacti smelt incorrectly

### ISSUE THREAD

**Issue by Greenzip** [Blood-Asp/GT5-Unofficial#410]
Hi! I've noticed that cacti have smelted into lapis lazuli dust. I've tried to delete all other mods (except ic2 and NEI) but i've got the same result.
![bug](https://cloud.githubusercontent.com/assets/16582985/12155398/f54ef86a-b4d5-11e5-9907-6068f7070881.png)

**Comment by Blood-Asp** [comment]
Certainly does not happen with GT+IC2 alone. I know about something similiar happen a while back because of Agricraft. The reason back then were strange oredict tags it added.
Another thing to test: regenerate configs and try in a clean world.
Lastly, does it happen in single or multiplayer? On servers it might be a sync issue.

**Comment by Greenzip** [comment]
I've tried in a clean world with new configs. It works. Thank you! That problem has happened in a single.
