### ISSUE TITLE
Idea:  Ethanol-fuel mix

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#414]
E-85 anyone?  85L Ethanol + 15L Light fuel = 100L Ethanol Gasoline Blend (EGB) or just E-85 as it's most commonly known.

LV recipe.  Same energy density as it's parent constituents, just a way to blend the two for a more homogenized fuel system than wierdly and awkwardly switching between ethanol and fuel and hoping a single 1L doesn't get stuck or something.

It would benefit me a lot, anyway!  Just an idea/suggestion.

**Comment by Blood-Asp** [comment]
I can't really see where this really helps. Building 2 generators instead of one generator and one mixer(and possible some fluid canners since there is no machine that can handle 2 input fluids) sounds much easier for me. Also since i can't define anymore new materials(max enum size reached), this also counts for fluids to burn.

**Comment by axlegear** [comment]
Ok.  Tho can't you regain some material definitions by removing unnecessary ones?  Example:  Terbium.  It has no use, can't be made, and seems to only exist in plasma form that I saw.
