### ISSUE TITLE
Timber Axe does not trigger Fast Leaf Decay

### ISSUE THREAD

**Issue by PaladinOne** [Blood-Asp/GT5-Unofficial#432]
There are a few mods out there that add some form of fast leaf decay, causing leaf decay ticks to occur quickly enough that once a tree is taken down, its leaves decay almost immediately. Annoyingly, the GregTech Timber Axe function does not cause this effect; leaves are left standing and slowly decay at their normal rate.

**Comment by JasonMcRay** [comment]
I have never had such issue. Sometimes with some trees with branches the logs are not being chopped by timber (timber functions cuts only logs in straight column). mayby thats what you are experiencing?

**Comment by MauveCloud** [comment]
Logs not chopped by the timber axe are more likely to prevent leaves from decaying at all by fast leaf decay mods (since they wouldn't get marked for decay).  However, leaves from other mods, such as greatwood leaves (Thaumcraft) or sacred oak leaves (Biomes O' Plenty) might not be handled by the fast leaf decay mods, similar to how breaking them with a GT branch cutter or Forestry grafter doesn't give the 100% sapling drop rate.  That might be what PaladinOne is encountering.  

In fact, I can state from personal experience that FastLeafDecay-1.7.10-1.4.jar by Olafski does not apply its effect to Thaumcraft Greatwood Leaves, but does work on IC2 rubber trees and vanilla Oak, Jungle, Birch, Dark Oak, and Spruce trees cut down with the GT Timber Axe effect (using GT 5.08.33).

**Comment by PaladinOne** [comment]
I'm on 5.09.19, and I'm having the issue with vanilla Spruce and Oak trees. And the Timber Axe effect isn't working at all on IC2 Rubber Trees (but RandomThings Fast Leaf Decay does).

Edit: And the fact that the leaves aren't getting marked for decay is probably the issue here.

**Comment by Blood-Asp** [comment]
For me does fast leaf decay work. But i know there are at last 3 different "FLD" mods, so maybe only some using certain ways do not work.

**Comment by PaladinOne** [comment]
Noted. I'll try to set up and test several variants to see if I can figure out which one is screwing up.

**Comment by Blood-Asp** [comment]
Some findings? Otherwise i will close this soon.

**Comment by JasonMcRay** [comment]
@PaladinOne I recommend using: http://mods.curse.com/mc-mods/minecraft/230976-fastleafdecay from Olafski. RandomThings for 1.7.10 are no longer maintained
