### ISSUE TITLE
Cannot fluid extract Americium

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#460]
Since GT 5.09.20 Americium can no longer be extracted into fluid with Fluid Extractor

**Comment by leagris** [comment]
Iron is the only Metal material that can be molten into a Fluid Extractor.
Or is it just NEI now hiding most of extractor recipes?

**Comment by Blood-Asp** [comment]
Fluid extraction counts as recycling. As the changelog says, recycling recipes are now hidden.
So please test if they really do not work, or are just hidden from NEI.

In all cases, i left the recycling recipes using iron behind so amounts and energy usages still show.
If you do not like that, you can unhide the recipes in the config.

Should too many complain about it, i might default to unhidden, so everyone can hide them if they want.

**Comment by leagris** [comment]
Ok, recipes works. But NEI Has important information about EU/t requirement to molten material.

Even if it may be straightforward to the chemistry educated, that you cannot molten tungsten in an LV Fluid Extractor, you still need to know the minimum tier to use.

I will change the corresponding config entry (thank you for the tip).

**Comment by Blood-Asp** [comment]
To show the required EU/t, it should be enough to only show one recipe per material, right?
For example only the ingot to fluid extraction recipe.

**Comment by OvermindDL1** [comment]
What about instead of hiding those recipes you enhance the NEI page that shows those recipes?  Perhaps even while the recipe page is up, which should always be shown when someone, say, hits 'r' on tungsten steel fluid and someone hovers over the tungstensteel fluid item in NEI, or anything else like Tin, then the popup shows the EU and such requirements for it as well.  That is easy to do with one of the forge hooks.
