### ISSUE TITLE
[Suggestion] export from input cover

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#471]
Could you add a cover that would allow us to export fluids (items) from the input tank of machines?

**Comment by Blood-Asp** [comment]
My idea was to copy the IC2s Solid/Fluid canners button to switch input&output tank. I only hope that that will not be too much work on the GUI side.

**Comment by MauveCloud** [comment]
Wait, how will that work for machines that don't have output tanks (e.g. Assembling Machine, Fluid Solidifier)?

**Comment by Nex4rius** [comment]
If you do that tank switch thing could you also add a redstone signal method of switching them?

Idea would press to a button and machine(s) gets emptied.

@MauveCloud good question

**Comment by leagris** [comment]
Another option that would make sense is: Not having fluid slots at all but have item slots where you place tank/fluid containers.
You should use IC2 Universal Fluid Cells that can contain variable amount of fluid and or implement variable amount of fluid inside GT large steel/tungstensteel GT Cells.
Single-block machines would use removable tanks in the forms of fluid containers instead of internal tanks.
Anyway, it is a too big change, too demanding logic and GUI code rework for @Blood-Asp time.
Still in term of automation (connecting power, fluid, item inputs and outputs) the most annoying machines are the chemical reactor, fluid canner and the electrolyzer. Those three would really benefit a much smarter piping system or a more permissive connexion.
Steve's Factory Manager and EnderIO conduits are great helpers/short-cut alternative to overly complex and bulky Gregtech pipings.

**Comment by Blood-Asp** [comment]
I choos the easiest way: https://github.com/Blood-Asp/GT5-Unofficial/commit/491a6d6c4b54000206c87438c381e11add40499d

**Comment by codewarrior0** [comment]
But... that's not much better than just wrenching the machine, no? 

I've made the mistake of putting fluids into a machine whose voltage tier is too low to use them, and I'd love to be able to get the fluid back out. ;)
