### ISSUE TITLE
Implement ic2.api.item.IBoxable

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#479]
Implement this for the GT Fuel Rods to be able to store them in Containment Box.

**Comment by MauveCloud** [comment]
The Containment Box is for radioactive hazards.  GT Thorium fuel rods are not radioactive, so there's no need for them to be storable in the Containment Box.

**Comment by JasonMcRay** [comment]
GT is overwriting also the normal Fuel Rods. Those are not able to be put in the Containment Box as well because of that. Also Thorium Fuel Rod is radioactive.... at least it is giving me radiation poisoning when held

**Comment by MauveCloud** [comment]
Sorry, forgot about the normal fuel rods being overwritten.  However, I tried earlier today starting in creative mode, gave myself a full stack of quad thorium fuel rods, and switched to survival mode, and didn't get the radiation effect.  Are you sure you didn't have something else giving you radiation?

**Comment by JasonMcRay** [comment]
Depleted ones are

**Comment by Timeslice42** [comment]
To be fair, it should only ever be the depleted rods (of any variety) that give radiation poisoning.

**Comment by MauveCloud** [comment]
Actually, some of the raw materials used in making the rods are treated as radioactive, and then there's plutonium and naquadah, which are radioactive even as ores (although plutonium ore no longer generates by default in 5.09).  However, some confusing details arise: 
1. Depleted thorium rods are radioactive, even though none of the materials that come out when thermally centrifuging them are (lutetium, thorium, iron).  According to Wikipedia, Lutetium has a stable isotope (atomic mass 175) and a mostly-stable isotope (atomic mass 176, half life 3.78e10 y).  However, based on https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/Element.java#L85 (the first parameter is protons, the second is neutrons), GregTech considers the default atomic mass of Lutetium to be 174, and that isotope has a half life of 3.31 y, so it should be radioactive, even if the decay products turn out to be impractical to add due to excessive lag or whatever.
2. U-235, U-238, and Pu-244 have half-lives of 7.04e8 y, 4.468e9 y, and 8.08e7 y respectively, so I'm not sure it makes sense for them to give radiation poisoning.
3. GregTech treats IC2 plutonium as being Pu-244, but http://wiki.industrial-craft.net/index.php?title=Plutonium indicates it's actually supposed to be Pu-239, which has a half-life of 2.41e4 y, making it somewhat reasonable for it to give radiation poisoning.

**Comment by Blood-Asp** [comment]
Added IBoxable, does not work... https://github.com/Blood-Asp/GT5-Unofficial/commit/91fc3a20cd09a47b80cb37279c89541dbb977b0d
Looking at Decompiled IC2 code, the Interface is never checked for the box.

**Comment by Timeslice42** [comment]
Wow, that's pretty lame.
