### ISSUE TITLE
Rocket Fuel for GC?

### ISSUE THREAD

**Issue by mura3277** [Blood-Asp/GT5-Unofficial#504]
So currently a GC fuel loader will accept GT Diesel Cells (but not ic2 ones strangely) as "Fuel".

Not sure which side this compatibility is on, but it would be a lot more interesting if instead of Diesel it was some sort of liquid rocket fuel from GT. 

A liquid oxygen and liquid hydrogen mixture might be the best option if you like the idea since it doesn't require new materials and makes sense for small rockets.

Thanks.

**Comment by Blood-Asp** [comment]
GT Diesel is registered as "fuel" in forge. Galacticraft only accepts "fuel" for it's rockets, so the issue is on GC side.

**Comment by mura3277** [comment]
Would you like the suggestion if GC accepted "rocketfuel" as well as "fuel"?

**Comment by Blood-Asp** [comment]
Then it would be little work for me to add such a fluid.

**Comment by mura3277** [comment]
So GC uses this method to check if the fluid name can be used in the fuel loader:

https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/FluidUtil.java#L48

It seems it is already checking if the fluid name has "rocket" & "fuel". Am I missing something or has GC changed this since last time you looked into it?

**Comment by Blood-Asp** [comment]
I did not know that was a thing in galacticraft... i guess i will add a rocketfuel that balanced around EnderIO rocket fuel. Or are there other well known mods with rocket fuel?

**Comment by mura3277** [comment]
I think EnderIO is the only mod that refers to a liquid as Rocket Fuel.

My opinion would not to balance it around EnderIO's rocket fuel (Or GC's) since if someone was like "Whats the easiest way to fuel my rocket" they would just use those two and not even consider GT's.

So I would say make GT Rocket fuel a lot more interesting (I like the Oxygen+Hydrogen mixture) and decently difficult for players who want to play GC with GT.

But of course, it's up to you.

**Comment by leagris** [comment]
I don't mean to be very serious, but I am lurking those unobtainable and unused Dilithium Crystals, Tritanium and Duranium since they are here to nag Star Trek fans.

I would be very exited to explore deep space using those Star Trek materials and Gregtech.

Dilithium and anti-matter for reactors and warp-drive.
Tritanium and Duranium for Ship structure.

Somehow, we already have kinds of replicators, and teleporters.

## On a more serious note:

Dilithium and anti-matter would make awesome ultimate density fuels.
Dilithium crystals to contain and regulate anti-matter reacting with matter in a controlled way.
Dilithium crystals degrade over time, so when they are toasted/degraded you regenerate them with some raw dilithium for re-use.
As Dilithium crystals are degraded, you avoid sending anti-mater into the reaction chamber or expose a very very large area to extreme damages.
Exploding an anti-mater reactor this way: Sending anti-matter into a reaction chamber without or with, out of order Dilithium crystals, would cause an explosion radius equivalent to a 3×3 IC2 Nuke.

Can have a MAX generator, but you pay with extreme risk if not handled properly. (Better take Need Maintenance signals very seriously). (Each defect adds 5% explosion chance on the next X Kticks if reactor chamber still contains anti-matter).

**Comment by mura3277** [comment]
I actually really like that idea. Of course it's a little off topic but definitely a cool idea.

Having an anti-matter reactor would be a cool awesome step up from normal fusion reactors. It could possibly use even harder to get casings and actually has the possibility to explode. My personal view is there shouldn't be a Max power source, but UV would be really interesting.

I also would really like a GT nuclear reactor since we're discussing reactors.

**Comment by draknyte1** [comment]
Take into Consideration that More Planets and other mods add far more progression to space and end game materials for space content is just stupid when you're only going to the moon.

**Comment by mura3277** [comment]
@draknyte1 I think @leagris was just brain storming on ways we could actually use the dormant materials in GT. I don't think she was saying to use a reactor to start off GC.

However on the subject of that reactor @leagris, you should really make a new issue/suggestion for that! I'd love to take a crack at adding it once I get the Diesel Engine done. The ultimate density fuel could by itself be a reason to add a new and interesting VERY late game generator.
