### ISSUE TITLE
Question about config

### ISSUE THREAD

**Issue by impaxel** [Blood-Asp/GT5-Unofficial#523]
What does "B:EnableAE2Integration_false=false" mean in GregTech\Other.cfg? That var looks weird :D For AE2 intergration I just should set true instead of second false, I guess?

**Comment by mura3277** [comment]
I'm going to guess that enables recipes like having to make the various presses in the precision laser engraver. If the AE2 press method was disabled, then it would delay AE until you were at HV/Extreme voltage.

**Comment by Blood-Asp** [comment]
That config enables functions that need direct access to the AE2 API. 
These functions are: Setting EU Tunnel with GT wires instead of IC2 cables that can be disabled and adding "rounds" as matter gun ammo.
This direct api access would crash when AE2 is not there in the correct version (AE2 rv2), so it defaults "false" when AE2 is not installed or for example rv3.
