### ISSUE TITLE
Fluid Filters don't work on some fluid (GT steams?)

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#538]
After hours of fighting, I have determined that while IC2 steam sets and passes a fluid filter correctly, GT steam is not recognized.
Both superheated and regular GT steams have been tried.  I tried sampling from a barrel, from a cell, and from a universal cell.  No go whatsoever.

**Comment by Blood-Asp** [comment]
Is the fluid filter fix here https://github.com/Blood-Asp/GT5-Unofficial/pull/568 this? @DEMOOH

**Comment by DEMOOH** [comment]
Yep. It just did nothing in case the fluid don't have a usual cell representative.
Edit: I have read the report again and my commit might not fix this. I made this one because the filter didn't work with toluene, which is different. But it might work since fluids are registered in both branches now. Probably, it worked correctly with GregTech cells only, but not with usual IC2 cells. I thought that those are basically the same thing.
