### ISSUE TITLE
IC2 Luminators not work with GT cables

### ISSUE THREAD

**Issue by Usernm0** [Blood-Asp/GT5-Unofficial#556]
If we use config option:
     B:DisableIC2Cables=true
We can't use luminators at all.

**Comment by yznpku** [comment]
Technically you can, because you can manually charge those lamps with IC batteries IIRC.

:)

**Comment by Blood-Asp** [comment]
you mean the crafting recipe is not changed to GT cables? hat is an easy fix.
Or do you mean that GT cables do not supply them mit energy? in case that does not work, the used energy interface is incompatible and nothing i can do.

**Comment by perkinslr** [comment]
They don't connect to GT cables, and GT cables don't supply them with power.  The problem is in TileEntityLuminator.acceptsEnergyFrom, it does an instanceof check against TileEntityCable.  Theoretically it would be possible to use reflection to make it count GT cables as an acceptable source, since it otherwise uses the standard IC2 power interface which GT already supports.  I'll leave it for someone better at reflection than I am.

Also note that you'd need to modify BlockLuminator.isSpecialSupporter to allow the luminators to be placed against cables.

**Comment by Usernm0** [comment]
GT cables not supply luminators with energy and I can't place luminators on gt cables

**Comment by Blood-Asp** [comment]
they can be placed on full blocks, so putting a cover on a GT cable should be enough to make it placeable on GT cables. Adding special code to GT cables to make them feed into iluminators feels too much work for what it is worth. also it might be a small performance issue.

**Comment by perkinslr** [comment]
Even with the a cover on the cable, it doesn't quite work 'right', it doesn't fill the full side, since it only does that for ic2 cables.  You're probably right that it isn't worth the performance implications to check if every nearby block is an ic2 luminator, especially since they won't work quite right anyway.  Also, unless the cover makes the block.isOpaqueCube() return true, it won't stick to the side regardless (they can go directly on battery buffers and transformers, maybe on cables with covers on each side).  

I've successfully made them work properly on my testing server, by editing the ic2 class files, and since it uses the standard energy net implementation, it doesn't adversely affect performance.  In theory, we could create a block that extends BlockLuminator, overload BlockLuminator.isSpecialSupporter and have it return true for GT cables, and then register the new GTBlockLuminator in IC2's block registry in place of the original (or maybe not even bother, just update the recipes to return GTBlockLuminator instead).  We'd have to do the same thing for TileEntityLuminator to remove the check in injectEnergy that prevents other energy sources.

**Comment by OvermindDL1** [comment]
Could just make a new GT-ified luminator that actually works properly.

**Comment by Blood-Asp** [comment]
Well, adding luminator covers for GT is something i tought of some time ago. no idea if i will ever get to do them.

**Comment by Blood-Asp** [comment]
Added to idea collection
