### ISSUE TITLE
Assembly line strange structure recalculations

### ISSUE THREAD

**Issue by Usernm0** [Blood-Asp/GT5-Unofficial#562]
After assembly line structure completed, I can remove all reinforced glass and all blocks on bottom middle assembly line except first and last one. http://i.imgur.com/j6zzSUT.png - this structure valid and works. If i remove something else and structure become incompleted, I need to put all reinforced glass back, but I can just remove first solid steel casing on bottom middle and put it back to make structure completed again.

**Comment by Blood-Asp** [comment]
GT only checks for blockupdates in the chunk involving GT blocks. I'm using IC2 blocks here, so that does not work. The machine will notice it is incomplete once something triggers a recheck of the structure. It's the cheapest blocks in the structure and it will detect soon enough to not be exploitable. So there should be no reason to fix it.
