### ISSUE TITLE
Assembly line books: item names not shown correctly on server

### ISSUE THREAD

**Issue by DerEchteLanger** [Blood-Asp/GT5-Unofficial#565]
I started making the data sticks/part list books on the IT2 server. Sadly everything which should e.g. show "Electric Motor (LuV)" reads something like "gt.metaitem.01.32606". This happens to the description of the book or datastick, but also inside the books itself. The strangest thing is that it works perfectly fine in SP.

**Comment by perkinslr** [comment]
This is because the server doesn't know the localization used, OpenComputers and ProjectRed's request pipes have the same problem with GT items.  The integrated server gets the same localizations as the client, so works perfectly.  I've tried poking in the GT source code to find the cause of the problem, but not been able to figure it out yet.  As a workaround, you can export the client localizations using minetweaker, and set them on the server also using minetweaker.

**Comment by Blood-Asp** [comment]
Also no idea where to begin searching for this issue... will likely take a bit until i get to it.

**Comment by Georggi** [comment]
Maybe this will help, but IC2 items, like Advanced Circuit are shown properly.
