### ISSUE TITLE
GT Ore in Thaumic Tinkerer KAMI's bedrock dimension

### ISSUE THREAD

**Issue by secirpac** [Blood-Asp/GT5-Unofficial#572]
GT Ore spawns incorrectly in the bedrock dimension. Maybe someone has already reported this bug.Is there any way to fix this?
![2016-07-19_14 35 44](https://cloud.githubusercontent.com/assets/16161401/16940710/2994d546-4dbe-11e6-952d-bd36ea40690b.png)

**Comment by OvermindDL1** [comment]
That is because they do not run the ore-gen calls so the GT ores never get setup, instead they just `setBlock` and forget, which is a bad bad bad way of doing it.  Need to report it to the devs to tell them to run the oregen code on the ore they setup.  GT is not the only mod their method will break.
