### ISSUE TITLE
Ore ignoring light level of adjacent blocks

### ISSUE THREAD

**Issue by mura3277** [Blood-Asp/GT5-Unofficial#575]
Is there any way to fix this? It doesn't happen if smooth lighting is off.
![image](https://cloud.githubusercontent.com/assets/7321570/17043273/f70b682e-4fac-11e6-9b52-f5552cf4d420.png)

**Comment by OvermindDL1** [comment]
It is actually correctly shaded, it just does not implement smooth lighting code (which is fairly simple to do, so it should...).

**Comment by mura3277** [comment]
Ah I see, I didn't know they were different calculations.

I launched up GT6 and it seems that this isn't an issue on there, so it could possibly be back-ported?

**Comment by OvermindDL1** [comment]
Greg added special code to handle that lighting.
And it is not a 'back-ported' thing, rather just need to implement the code.  It is a bit hairy since no good helpers have been made yet, but not too hard.

**Comment by Blood-Asp** [comment]
I decided not to touch the rendering code. Last time i did it just made everything worse. And properly learning how that all works takes too much time for such small visual issues. Especially when moving to 1.10 would change that all anyways.

For now i will leave this open in case someone wants to try this as PR. Otherwise i will close the issue in a few weeks.
