### ISSUE TITLE
[Interaction] Recipe Loop with ChromatiCraft

### ISSUE THREAD

**Issue by SeppDE** [Blood-Asp/GT5-Unofficial#590]
Hey there,

For the last versions there is something broken with GregTech 5u and ChromatiCraft.
If you look for the usage of an item who got an recipe involved in Gregtech there is an loop of recipes which last up to one hour. I tested both versions of GT5u (08 and 09) which ended up the same.
If you waited one time you can instantly look for the Usage the next time. But if the server/SSP is restarted, the process start again.

Used Versions:
Forge: 10.13.4.1614
IC2-exp: 2.2.822
GT5u: 5.09.22 and 5.08.33
DragonAPI: 15a
RotaryCraft: 15a
ChromatiCraft: 15a
ElectriCraft: 15a
Reactorcraft: 15a
NEI: 1.0.5.120
CodeChickenCore: 1.0.7.47

Log GT 5.09 https://gist.github.com/SeppDE/1359f35029842dc9ffebd90ee67503b9
Log GT 5.08 https://gist.github.com/SeppDE/a5212cc1899678937c2cc62c41372560

**Comment by Blood-Asp** [comment]
First: The logs are cut off, nothing to see up to the point they are there.

Trough the linked issues i could find this log: https://zerobin.net/?4ba091e6872c987c#8CIZ8IjOlEaEKUgdJueoN5R6A6m7Qbi6cpuyJBA9E4U=
There i see laggy interaction beween GT and ChromatiCraft. But it is no loop, but really just a laggy recipe scan ChromatiCraft does on GT recipes, likely trough NEI. GT adds something like 30k+ items and easily 150k recipes for them. Either Chromaticraft does not handle so much in the first place or broke some optimisations.
Also not sure what exactly does happen here while reading the log. Chromaticraft finds recipe loops. That either because of the recycling recipes that return items back into dusts/ingots and can be used to make them again, or somehow mixes up all the metaitems and sees different items as the same.

But in the end, i see no reason why GT should be at fault here. GT5.08 is months old and worked all the time.

**Comment by SeppDE** [comment]
The full version of the log is in the top part of my gist. There is an Link to the full file in .txt format because it's too long for Gist too. (Pastebin can't handle it too.)

CC seems to look for every recipe and the log shows thousands of messages like this one (same as the ones in the zerobin.net link)

> [16:21:17] [Client thread/INFO]: CHROMATICRAFT DEBUG: Calculated for 1xgt.metaitem.01@23500 (Diamond Rod): {}
> [16:21:17] [Client thread/INFO]: [CHAT] DEBUG: Calculated for 1xgt.metaitem.01@23500 (Diamond Rod): {}
> [16:21:17] [Client thread/INFO]: CHROMATICRAFT DEBUG: Recipe contains its own output, possibly recursively.
> [16:21:17] [Client thread/INFO]: [CHAT] DEBUG: Recipe contains its own output, possibly recursively.

As far as i understand CC take a look on all recipes to calculate the different costs for it's own recipes. This is the reason why it takes so long to finish the process. It seems to "save" the results at least for the active server uptime. If you restart the client/server the whole process start again.
As far as i can see the log only output items from GT - for me it sounds like anything in GT is changing every start of the game which trigger the recipe scanning from CC again or CC does not save the progress of the last scanning.

**Comment by DEMOOH** [comment]
Can you try to install just IC2 and this mod and look for the same messages after some restarts?

**Comment by Blood-Asp** [comment]
Seems Reika fixed it.
