### ISSUE TITLE
Forge Versions [Inquiry]

### ISSUE THREAD

**Issue by draknyte1** [Blood-Asp/GT5-Unofficial#596]
> Forge versions 1428-1480 are known to break multiplayer.

Why exactly?
I've ran against 1448 since release without a single issue for my live server, just don't see why it's listed as breaking multiplayer when hundreds of players and I can attest to that.

**Comment by Blood-Asp** [comment]
The Forge Fluid list Syncronisation on Server join was broken in these versions.
As long the Fluid list stays unchanged since worldgeneration, everything works fine even with Multiplayer.
But usually Simply updating Mods or change g Mods inside the Modpack will change the order of the fluidlist.
Once that happens, Clients joining a server potentially crash. Not allways but often enough that the forum was full of bugreports about it. This could happen with every modpack, not just these with GT installed, but the way GT is coded made it happen quite often.
There is also an issue on the Forge GitHub about this going into details.

**Comment by draknyte1** [comment]
I started with 150 mods in my public pack and now have 202.. Changing them hasn't effected my fluid registry/list at all.. Nor has any user ever reported an issue..

The singular issue I've seen personally is no fluid icon for helium.. 
Otherwise nothing described by you or forge has ever happened.

**Comment by OvermindDL1** [comment]
> The singular issue I've seen personally is no fluid icon for helium.. 

That is likely a symptom of the broken forge issue.  You got lucky.

**Comment by draknyte1** [comment]
It's been like that since world generation.. 
Not since any mod changes.

**Comment by Blood-Asp** [comment]
That's likely Galacticraft. Overriding GT fluids without registering a Fluid Icon. Should be fixed in newest GC versions.

And as I said, the Forge crash does not happen always. I know how to replicate the bug so it got fixed. In your case, you simply got lucky.
