### ISSUE TITLE
Disassembler refuses to work

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#601]
I have Advanced Disassembler II (HV) supplied with energy. It should work, but when I place machines in it, it does nothing. I have tried to disassemble Advanced Disassembler I (MV) and Advanced Compressor I (MV) so far and it didn't work.

Using version 5.09.22.

**Comment by Blood-Asp** [comment]
For the disassembler to work, the machines need an NBT tag of its components that is applied while crafting them.
Machines made by none vanilla crafting or cheated in do not have that NBT tag and can not be disassembled. To be sure the tag is there, you can for example test the item with "/mt hand" when you have minetweaker installed. I'm sure there other ways to read the NBTs, but this is the one i usually use.

In case the tag is missing, you can still recycle the machines in the arc furnace, macerator or fluid extractor. Just not into components but raw materials with likely some missing.

**Comment by leagris** [comment]
Le 17/08/2016 à 22:25, Antillar a écrit :

> I have Advanced Disassembler II (HV) supplied with energy. It should
> work, but when I place machines in it, it does nothing. I have tried to
> disassemble Advanced Disassembler I (MV) and Advanced Compressor I (MV)
> so far and it didn't work.
> 
> Using version 5.09.22.

Disassembler woroks only on stuffs that were crafted, not stufs from
give or creative, because components are stored as NBT Data.

@Blood-Asp, if not too much work. I suggest the following:

Add special Lore to creative-tab items stored as NBT and kept even on
block placement.
Creative-tab items shall also sstore the PlayerName and UID. So any
machine or component obtained in creative sshall be permanently tagged with:
`"Obtained in Creative from: playerName"`

Any gregtech Machine/Block/Component obtained from the Give command
shall be tagged with:
 "Give item from: playerName/Console"

Lore shall also mention:
"No disassembly possible"

Such items shall also be denied pulverization, hammering, smelting, arc
furnacing. (or simpsly vanish if inserted into these machines, gives no
output materials).

Optionally, creative/give machines shall default to owned/locked by
OP/giver/creater (no placement, no inventory interaction, no removal if
not owner. Same as putting a lock upgrade into a machine).

## 

Léa Gris

**Comment by Antillar** [comment]
I have these items crafted and placed by hand, but this happened before I updated to this version from a very old one (5.03 or smth) so this may be an issue with updating. Thanks for fast answer anyway.

**Comment by Blood-Asp** [comment]
version 5.03? So old no wonder it did not work...

@leagris Thats likely really quite a lot of work. Some parts more, others less but overall i see this as too complex for the gain from it. Creative/Cheat should be taken care of by the serverowners, not be even more work for modders.
