### ISSUE TITLE
Missing material

### ISSUE THREAD

**Issue by basdxz** [Blood-Asp/GT5-Unofficial#609]
So we have elements like Naquadah and Naquardia but we appear to be missing everyone's favorite mineral: Trinium You can read about it here: http://stargate.wikia.com/wiki/Trinium. Would be great if you could improve my immersion by adding this ore to the Naquadah alloy crafting recipe. Please fix this game breaking bug ASAP!

**Comment by mura3277** [comment]
Well before we could not add new materials due to an enum limitation, but that will soon be fixed. So I guess there wouldn't be a reason not to include this material other than not being able to think of a good use for it. Currently (Not sure if in a released build) but Naquadah Alloy has a recipe now, but it might make more sense for it to use this vs Osmiridium.

**Comment by Blood-Asp** [comment]
Added to idea collection
