### ISSUE TITLE
Wrong recipe with Aurelia Leaf

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#634]
Basic Chemical Reactor recipes
- Crushed Magnetite Ore + Ferru Comb = 4x Purified Magnetite Ore - Ok
- Crushed Magnetite Ore + Ferru Leaf = 4x Purified Magnetite Ore - Ok
- Crushed Magnetite Ore + Aurelia Comb = 4x Purified Gold Ore - Ok
- Crushed Magnetite Ore + Aurelia Leaf = 4x Purified Magnetite Ore - Seems like mistake

**Comment by DEMOOH** [comment]
Ore transformation is a feature of the combs. There are some similar recipies only for combs.

**Comment by SapientMC** [comment]
Hm.. I thought crops breeding are more difficult than bees breeding and should not be less effiсient.

**Comment by Blood-Asp** [comment]
combs and crops should have the identical output, so issue is valid i guess.
Imho bees are worse to breed, but crops more difficult to set up huge fast farms.
At last are bees worse without binnies or gendustry.

**Comment by leagris** [comment]
bees are less random and more practical about environment than IC2 crops.
One thing I regret about GT bees is they don't really enforce exotic biomes and blocks requirements for breeding and jubilant requirements for specialty production.
Having these for GT Bees would adjust difficulty in even pair with crops.

**Comment by leagris** [comment]
Just one example.
Instead of having iridium bee produce iridium combs. You would have it produce iridium and osmium combs as specialty only. Choose one of the uncomfortable biome as jubilance rule.
If possible, find mean to integrate bees and crop against pollution (decrease output of bees in polluted chunks, or add chance of death/decay).
