### ISSUE TITLE
Pollution does not disperse.

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#661]
If any polluted chunk has no active burner, pollution does not disperse at all.

**Comment by Blood-Asp** [comment]
i know that pollution in unloaded chunks that never got triggered does not tick, so also not disperse, but not having a active burner should not change anything here.

**Comment by SapientMC** [comment]
It's loaded chunk. I'm there. Just turned off 20 lava boilers. And pollution rate does not change for several minutes.

**Comment by Blood-Asp** [comment]
I could not yet see this behavior in my dev enviroment. Can you find the exact way to get this?

**Comment by mightydanp** [comment]
what is pollution going to do

**Comment by SapientMC** [comment]
@Blood-Asp I just built 2 small boilers in near chunks. They works some time. I destroyed them.
Look at time and pollution level.
![2016-10-03_10 25 19](https://cloud.githubusercontent.com/assets/14032818/19031413/d2c9ecc6-895c-11e6-93c6-eadc87f54f7e.png)
![2016-10-03_10 25 37](https://cloud.githubusercontent.com/assets/14032818/19031414/d2de9e5a-895c-11e6-9ce5-14925e075326.png)
![2016-10-03_10 27 11](https://cloud.githubusercontent.com/assets/14032818/19031415/d2e609d8-895c-11e6-8dfd-b4ad2a9d218e.png)
![2016-10-03_10 27 25](https://cloud.githubusercontent.com/assets/14032818/19031416/d2f710b6-895c-11e6-8f31-608c3cda3e6b.png)
![2016-10-03_10 29 36](https://cloud.githubusercontent.com/assets/14032818/19031417/d301ee28-895c-11e6-9e71-5143d466c960.png)
![2016-10-03_10 29 50](https://cloud.githubusercontent.com/assets/14032818/19031418/d320fd72-895c-11e6-820f-d18affbe3ef5.png)

I could upload modpack and save if needed.

**Comment by SapientMC** [comment]
Additional info. Seems like pollution does not disperse only if value are below 2000.

**Comment by Technus** [comment]
@Blood-Asp you can try looking at my changes in GTNH repo, seems like it is better to use >>4 at all times I also removed the unnecessary conversions from the pollution code (like *16 /16 was happening sometimes for no reason), and did some code changes that might correct that issue too if I am right.
(just ignore the changed numericals i have for more pollution ;])

**Comment by Blood-Asp** [comment]
I did take some of the fixes, thanks for that, but also noticed that you disabled some stuff that had an actual use...
https://github.com/Blood-Asp/GT5-Unofficial/commit/7926877ed18689ebca2fc170627bcb61d5ac13c0

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/GT_Pollution.java#L33 <- is needed once there are more than 1200 chunks with pollution. Otherwise the processing will start to disort after hitting that limit. And a server with multiple bases will hit that limit quite fast.

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/GT_Pollution.java#L45 <- Is the main factor for lowering the pollution. Because of that, <10 bronze boiler or just one single multiblock are enough for completely killing your world with pollution.

**Comment by Technus** [comment]
Idk if it is intentional but iirc pollution block is 10k and then in muffer u make it 1k so the effective pollution per tick at 0% reduction is actually 10x smaller.

**Comment by Technus** [comment]
Also if u want i have some simple program written in processing to simulate pollution spreading lol.

**Comment by Blood-Asp** [comment]
sure. so far i only estimated the spreading. Seems i rally forgot a zero in the muffler.

**Comment by Technus** [comment]
https://github.com/Technus/PolluteSim9001/tree/master
Pushed the sim code here

Also if u browse the GT code a bit there are chances you will find my code for particle generation from mufflers.

**Comment by OvermindDL1** [comment]
@Technus What language is that even?  Kind of java'ish, ...yet not (there are globals?!)...

To see how it looks I tried to replicate the code at http://overminddl1.com/bucklescript/ (click the GTPollute button), is that close?  Also I'm unsure what specific values the game itself uses but it seems to propogate quite fast.  ^.^

**Comment by Technus** [comment]
Github has the thing called readme.md tried reading?

**Comment by Technus** [comment]
It is processing, which is java. The whole file is a class in that ide.

**Comment by Technus** [comment]
Also it is not fast. Just the simulation runs at least 10k x faster (normally one pollution spread happens per 60 s in bloodasp code and then my thing runs it in a thread limited only by cpu power) since it is used to estimate quasi stable states where pollution in=pollution out

**Comment by OvermindDL1** [comment]
> Github has the thing called readme.md tried reading?

```
Simulates GT5u Pollution if u have the correct values

Done in Processing 3.2

required libs:

g4p
```

That tells nothing about how to set it up, the commands to run, what packages I'd need to apt-get, etc...  ;-)

> It is processing, which is java. The whole file is a class in that ide.

What is it processing, just the pollution?

> Also it is not fast. Just the simulation runs at least 10k x faster (normally one pollution spread happens per 60 s in bloodasp code and then my thing runs it in a thread limited only by cpu power) since it is used to estimate quasi stable states where pollution in=pollution out

I figured, it ran _way_ too fast in the browser so I had to throttle it to something to where I could actually view it grow (it is oddly fun to watch!), 50ms seemed good from a couple quick tests.  :-)

EDIT:  60s in-game seems like a good growth, although if it does that thing where it is weighted to the up/left that should be fixed.  I was almost tempted to fix that code in the browser one but figured that it was weighted like that for a reason.  To evenly and properly distribute it should add up what it can push to around it, make a diff based on that, then distribute, would be perfectly even then.

**Comment by Technus** [comment]
...
https://processing.org/
no commands no special settings just install that and the lib from gui in the program

yes even slight delay makes the code look better but actually require more time to get to stable state

**Comment by OvermindDL1** [comment]
> https://processing.org/
> no commands no special settings just install that and the lib from gui in the program

They picked a **really** unfortunate name.  ^.^
I'm not able to find it in the apt repositories, is the website the only way to get it?  How... odd.  o.O

And it does not seem to work, trying to load your repo only lets me choose one file or the other, choosing either makes it say that it refuses to open the file since the file is not in a directory of the same name as the file, though it offers to fix it, and if it does clicking 'run' on either does nothing, and I did install the `g4p` library from the menu (before that it would not run because of missing library anyway).  I grabbed the latest stable version.

EDIT0:  The examples in Processing 3.2.1 are working fine, but neither of your files work.

EDIT1:  The messages I get about the files for note:
![image](https://cloud.githubusercontent.com/assets/401605/19730447/8106459e-9b57-11e6-975f-023d9e372f19.png)
![image](https://cloud.githubusercontent.com/assets/401605/19730453/86d0d610-9b57-11e6-8ad5-e721ebf477df.png)

**Comment by Technus** [comment]
yes, their way of making projects is bad since u need a "sketches" dir that holds folders with sketches that have the same names as the folders, uhh....
[sketch_161002a.zip](https://github.com/Blood-Asp/GT5-Unofficial/files/553541/sketch_161002a.zip)
This is how i have it setup inside the sketches folder.

(Casually issue changes to some conversation...)

**Comment by OvermindDL1** [comment]
Awesome, I'm always interested in checking out a new language setup.  :-)
Ignore this, sec...

**Comment by Technus** [comment]
yes install g4p lib i dont see tickmark on libraries page

**Comment by OvermindDL1** [comment]
> yes install g4p lib i dont see tickmark on libraries page

Yeah it apparently needed a restart before the checkmark appeared, it is running now.  :-)

I'm wondering if a slider would be better as a value, or perhaps maybe clicking a cell and setting a value so you could have multiple areas where pollution appears to see how the different masses interact?

**Comment by Technus** [comment]
possibilities exist yes

**Comment by OvermindDL1** [comment]
Also for note, your g4p builder is out of date.  :-)

![image](https://cloud.githubusercontent.com/assets/401605/19730877/d1b6fb0e-9b58-11e6-9764-bbb054b451c2.png)

**Comment by Technus** [comment]
nah my g4p lib is outdated and broken :dagger:, doesnt want to update yet i am too lazy to fix it

**Comment by OvermindDL1** [comment]
> nah my g4p lib is outdated and broken 🗡, doesnt want to update yet i am too lazy to fix it

Lol, oh the age-old problem of any programming language it seems.  ^.^

The pollution cloud actually gave me an idea for another quick-play clicker like I have on that same site, but with cellular automata, hmm...

**Comment by Blood-Asp** [comment]
Too much time since i was on this. Can someone test the .27pre build to test if it is fine now?

**Comment by SapientMC** [comment]
@Blood-Asp Nothing changes. Pollution still stops decreasing if value are below 2000.
