### ISSUE TITLE
GT5 config-Machine Stats: Steam turbine efficiencies

### ISSUE THREAD

**Issue by Vitium92** [Blood-Asp/GT5-Unofficial#697]
As the title says, in the .25 version of GT5-u the steam turbine efficiencies are set in the config file with the form

```
I:SteamTurbine.efficiency.tier.0_6=6
I:SteamTurbine.efficiency.tier.1_7=7
I:SteamTurbine.efficiency.tier.2_8=8
I:SteamTurbine.efficiency.tier.3_9=9
```

instead of the other generators' efficiencies, such as 

```
I:DieselGenerator.efficiency.tier.0_100=100
I:DieselGenerator.efficiency.tier.1_95=95
I:DieselGenerator.efficiency.tier.2_90=90
I:DieselGenerator.efficiency.tier.3_85=85
```

which makes difficult to guess what number is equivalent to a percentage in the former case without shutting down the client/server and restarting it. Could it be possible to set them as a percentage like the other ones?

**Comment by SapientMC** [comment]
percentage = 600/Value_from_config/100
T1 - 85,71%
T2 - 75,00%
T3 - 66,67%
And there are no T0 steam turbine.

**Comment by Blood-Asp** [comment]
The calculation for steam turbines has to be done differently because of the low energy density of steam. Making the other generators configurable with percentages already causes that sometimes low amounts of fuel stay inside that can not be used up. For the steam turbines that would mean it had to store up about half the internal tank and turn it into energy in one step. Turning on/off all the time would also lag quite extreme.
