### ISSUE TITLE
Incorrect Maceration/Pulverization recipes

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#705]
(vanilla) Stone furnaces **Macerate** into 8 stone dust (which is correct), however they **Pulverize** into 8 sand (which is wrong). According to IC2 the only stone related item which is supposed to grind into sand is cobblestone; everything else (stone, slabs, machines, etc.) grinds into stone dust.

**Comment by Nex4rius** [comment]
You could always turn furnaces into sand in a macerator.

**Comment by Blood-Asp** [comment]
I somehow want to keep the furnace = 6 sand recipe... always used it for mass sand production.

**Comment by PaladinOne** [comment]
Maybe some sort of recipe that converts Stone Dust into Sand?

**Comment by Timeslice42** [comment]
@Nex4rius I'm actually trying to turn stone furnaces into stone dust, but sadly the steam macerator is a pulverizer, not a macerator. Or something...

**Comment by yznpku** [comment]
I believe this recipe is actually a feature.

**Comment by Bogdan-G** [comment]
ancient bug, i have seen it 2 years ago.
2 recipe conflict and overlap randomly at each other at every startup. The solution is simple: to regulate all the recipes, or check and remove for solve the conflict. Not only ic2 adds cobblestone crushing recipe in the sand in crushers.

ps in IRL sand and stone dont 1 type.

**Comment by Timeslice42** [comment]
I'm not sure what "dont 1 type" means, but in the same way that gravel isn't sand, sand isn't dust. Think of stone dust as crushed sand.

But yeah, it's the fact that the recipes are inconsistent that bothers me the most.

**Comment by MauveCloud** [comment]
Personally, I think something like this would make somewhat more sense:
Anything made with a significant amount of stone/cobble (including furnaces and straight cobblestone) in a macerator/pulverizer produces stone dust.
Cobblestone can already be hammered for gravel.
Gravel can be forge hammered to get sand, or sifted to get flint (and maybe also macerated/pulverized for stone dust), instead of macerated for flint and washed for stone dust. (I mean, how does that make any sense?  water reduces it to dust, while a macerator with a diamond grinding head leaves a big piece of flint behind?)

**Comment by Bogdan-G** [comment]
@Timeslice42 

> "dont 1 type"

subtypes stone and sand a lot in real life, and in terms of the reality of crushed rock not can be yellowish sand with impurities. Stone and sand is a generalization of the name of the substance groups and formations, I understand that we play the game, there is a lot of oversimplification. But if we want to make by analogy from the real world, we must turn to what source?

**Comment by Timeslice42** [comment]
@MauveCloud Sounds like a great candidate for a PR...

The only tricky part I see is that we'd still need to use a mortar to get flint from gravel (a.k.a. "grind" it), since there is no hand powered sifter.

@Bogdan-G What's really bizarre is impure stone dust. It's stone dust made impure by a small amount of... stone dust in it.

**Comment by MauveCloud** [comment]
@Timeslice42 No hand powered sifter?  What about the scoop?  It's made with wool and is used to obtain bees and butterflies (if Forestry is installed), so it's basically a net, which should be able to sift flint out from gravel.

Edit: I ran into a different tricky part: the ore washer recipe for gravel to stone dust is from IC2 rather than GT, and as far as I can tell, IC2 doesn't provide an API method for removing/disabling that recipe (copying ore_washer.ini from the jar to config/ic2 and commenting out the line works, but that's not appropriate for GT to do automatically)

Edit 2: further investigation revealed a GT_Utility method for removing IC2 machine recipes, which is already used for removing things like the compressor recipe for energium dust to energy crystal (GT uses the autoclave instead) or the extractor recipe for sulfur from gunpowder.

**Comment by Timeslice42** [comment]
That's awesome. I'm going to have to remember GT_Utility for the future as well. The scoop is a bit of a stretch, but could work. The only problem being that it is far more expensive to craft than a flint mortar. If only wooden scoops were a thing...

**Comment by MauveCloud** [comment]
The metatool system should allow adding a wooden scoop that doesn't require tools to craft (similar to a flint axe, shovel, etc.), perhaps with a plank in the center to avoid conflicting with Forestry's standard scoop recipe in case the mod is installed.
