### ISSUE TITLE
[1.7.10] Canning Recipe issues

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#722]
It looks like the gregtech canning machine is generating some of its recipes incorrectly. The example I found was this:
2 rotten flesh + 1 tin can -> IC2 canner = 1 canned food
1 rotten flesh + 4 tin can -> GT canner = 4 canned food

I'm hoping that's the only discrepancy, but I doubt it.

**Comment by codewarrior0** [comment]
Looks like the canned food values for Rotten Flesh and a few others are hardcoded, instead of being derived from the food's nutrition value. If there are other discrepancies, they would be Spider Eye, Poisonous Potato, Cake, and Mushroom Stew.

https://github.com/Blood-Asp/GT5-Unofficial/blob/a03fc7fc1dcc57168e567fbdd09afdd895ce2570/src/main/java/gregtech/loaders/load/GT_ItemIterator.java#L49

While we're on the topic, does it seem to you like the canned food amounts ignore what Hunger Overhaul does to reduce all food's nutrition values?

**Comment by Timeslice42** [comment]
I wouldn't be suprised if the HO food values aren't happening until after GT creates the recipes. As for the canned food itself, it's not even technically food. It is (yet another) hacky piece of IC2 code that consumes a can for each half haunch missing and directly adds the corresponding food and saturation value to you.

**Comment by Timeslice42** [comment]
Looks like chum is giving way more canned food than it should as well.
