### ISSUE TITLE
Several recipes questions

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#724]
1. In modpack w/o Thaumcraft we have no recipe for Magic Solid Super Fuel. But we have at least one available for Magic Super Fuel Binder (from Mercury). So why we can't craft MSSF?

2. All Field Generators has Assembler recipes and same material cost but zero energy cost shaped recipes. Why shaped recipes are not disabled?

3. Why Mining Laser recipe requires just one variant of Exquisite gem? Think is should have some red alternative (Ruby / Jasper / Red Garnet).

**Comment by MauveCloud** [comment]
> All Field Generators has Assembler recipes and same material cost but zero energy cost shaped recipes. Why shaped recipes are not disabled?

I think some assembler recipes are to allow automation of them when GT is used without other mods for auto-crafting.  I mean, do you want to disable crafting recipes for things like chests, stone bricks, and 2x, 4x, etc. wires just because there are Assembler recipes for them (that don't involve eliminating tool requirements or reducing material costs)?

> Why Mining Laser recipe requires just one variant of Exquisite gem? Think is should have some red alternative (Ruby / Jasper / Red Garnet).

That's only one of the problems with the new recipe for the mining laser.  A charging lapotron crystal (which stores 40 million EU) to make a mining laser that only stores 300 thousand EU?  IV-tier circuit, and EV-tier emitter for an HV-tier tool?  Also, why doesn't it have a lens somewhere in the recipe?

**Comment by SapientMC** [comment]
> do you want to disable crafting recipes for things like chests, stone bricks, and 2x, 4x, etc.

No. Field Generators are hi-tech devise and not require any tool but pretty high tier of assembler. Crafting them on table instead using 2kV mechanism - yes it's cheet.

> That's only one of the problems with the new recipe for the mining laser.

Agree. But all of them are a little less important (but still are) for me. Because current recipe makes it very rare. Too rare.

**Comment by Blood-Asp** [comment]
Fixed MSSF.
The Field Generator Assembler recipes got added to allow making field gen with dusts instead of gems. Needs energy, but you have a use for your netherstar dust.
Made little changes to mining laser + alternative recipes.
