### ISSUE TITLE
Bug with liquid heat exchanger

### ISSUE THREAD

**Issue by Pilad** [Blood-Asp/GT5-Unofficial#742]
With Gregtech 27pre 80heat units of 100 exchanges
http://imgur.com/a/WQBHy
Without GT 100/100 (only IC2)
http://imgur.com/a/DG3Vk

Whis is bug?

**Comment by Pilad** [comment]
Reactor generated 100HU, but four LHE show in interfaces 80/100 , how is it possible?
http://imgur.com/a/HpSEJ
But they( 4 LHE ) can be exchanged 400HU, but reactor produces 100HU.
And that is true for both rods thorium and uranium.
http://imgur.com/a/8R5JK
And the four LHE  can not exchange heat the reactor. 
And overheat and booomm )))

**Comment by OvermindDL1** [comment]
OhGod, why are you using a website to host images that have NSFW AD content?!  Use imgur or, heck, just use github as you can paste an image straight into this markdown box...  >.>

**Comment by Pilad** [comment]
I use firefox+adblock and no NSFW AD content. Ok , re uploads images.

**Comment by OvermindDL1** [comment]
> I use firefox+adblock and no NSFW AD content. Ok , re uploads images.

I am at work, and we do not always have the choice to customize our browsers.  ;-)

Why would such a website ever be used for image uploading anyway?  You literally can just copy/paste an image straight into a comment, like this:
![image](https://cloud.githubusercontent.com/assets/401605/20146383/fafe10ca-a660-11e6-9174-6e87a882a574.png)

EDIT:  You can make it collapsable too if you want, like this:
<details> 
  <summary>

Expand me to see image of something</summary>


   ![image](https://cloud.githubusercontent.com/assets/401605/20146383/fafe10ca-a660-11e6-9174-6e87a882a574.png)
</details>

**Comment by Blood-Asp** [comment]
The issue comes from the improved heat value per amount of hot coolant to make reactors better with GT installed. The smallest conversion amount before was 10HU for 1L hot coolant. I rised it 4x. That still works, but results in the smallest unit beeing 40HU for 1L hot coolant. Now the biggst fitting amount becomes 80HU instead of the 100HU before. But at last it only uses 2L HC instead of 10L HC. I might rise the improvement to 5x to make that better, but i will not improve the Large Heat Exchanger anymore. That one is powerfull enough. Just that would make the two different heat exchangers having different efficiencys...

**Comment by Pilad** [comment]
I would like to see the opportunity. It would be desirable to heat exchanger IС2 also worked.
