### ISSUE TITLE
[Open Request] GT Drills in IC2 miner

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#753]
This is an open request to anyone in the community (which includes Blood Asp) to add GT drills to the tools that the IC2 miner will accept. This is not a trivial change and would require ASM to accomplish. The EU usage statistics for the Miner are listed here: http://wiki.industrial-craft.net/index.php?title=Miner

As near as I can tell the miner "uses" the internal drill and scanner (consuming EU from them) and recharges them from its internal EU buffer. There's a question as to whether the miner should accept anything higher than LV drills, since it's an LV machine.

This change could be implemented in multiple phases:
Phase 1: The Miner accepts any GT drill and consumes an arbitrary amount of EU from it per operation.
Phase 2: The Miner actually "uses" the GT drill on each block it mines, thus consuming the correct amount of EU and damage from the drill.
Phase 3: The Miner factors in the mining speed of the GT drill when determining its own mining speed.

**Comment by Timeslice42** [comment]
This (and a few minor recipe changes) are all that's standing in the way of GT being able to disable all of the IC2 power tools. Not that the electric tap really needs to be disabled, but does anyone ever use that anyways?

**Comment by MauveCloud** [comment]
Wait, what about the mining laser?  GT doesn't have its own version of that, and unlike the drill/chainsaw, it actually makes sense for it not to take durability damage when mining.  There's also the electric hoe, but GT at least has non-electric metatool hoes.

Also, I'm puzzled by this request - GT5e has the Advanced Miner II, so does anyone playing the mod actually use the IC2 miner instead?

**Comment by Nex4rius** [comment]
The Advanced Miner II is an EV machines but the IC2 miner can be used alot earlier in MV and its slower with a lower radius (9x9) and doesnt pulverize the ores. Its a good early game automated mining machine without being overpowered. I would use this if it hadn't been disabled in the InfiTech2 modpack because all IC2 drills are disabled.

**Comment by leagris** [comment]
The IC2 Miner has not those strange bugs as AdvMinerII from GT. It does not mine ores from other dimension, has whitelist and blacklist, can operate on less batteries, does not require fixing defect with 7 different tools + those different casings and frames. Can work outdoor exposed to rain without exploding or at least does not require you to transport shielded battery buffers, does not require you to carry thousands Liters of drilling fluid on site. Overall it is easier to deploy and use at remote locations.

**Comment by draknyte1** [comment]
Ask the IC2 Devs for Compat..  It's not an issue for someone who uses the IC2 mod as it's intended (With IC2 drills)

Gregtech as a replacement mod for IC2, gives you a miner, moves it back tech wise later game and gives you more depth. No reason we should add compat for it when we've added a multiblock replacement miner.

IC2 features are for them. If they won't do it, I'd suggest avoiding it... or...
If the IC2 drills are gone, ask Jason to add ASM support to their Horizons Pack core mod (not an actual CoreMod I don't think but it's the basis of their modpack and the most suitable place for hacky ASM stuff, which is what it in itself truly is.)

**Comment by Timeslice42** [comment]
Until Gregtech is completely decoupled from IC2 it is _not_ a replacement for IC2, it is merely a companion to IC2. Gregtech is IC2 extended. The GT miner is not meant to be a replacement of the IC2 miners, but as a higher tier multi-block version of them.

@MauveCloud I forgot about the electric hoe, but as GT doesn't have it's own electric hoe I don't see why it would need to be disabled. As for the mining laser, I don't consider that a traditional power tool.

**Comment by MauveCloud** [comment]
> Until Gregtech is completely decoupled from IC2 it is not a replacement for IC2, it is merely a companion to IC2. Gregtech is IC2 extended. The GT miner is not meant to be a replacement of the IC2 miners, but as a higher tier multi-block version of them.

Good point, but since IC2 is still in active development (unlike, say, Binnie's Mods, even if the IC2 dev team is more focused on the 1.10.2 builds), I agree with draknyte1 that requesting infrastructure to support this in the suggestions section or the IC2 bug tracker would be more appropriate than ASM hacks.

> I forgot about the electric hoe, but as GT doesn't have it's own electric hoe I don't see why it would need to be disabled. As for the mining laser, I don't consider that a traditional power tool.

You were talking about disabling "all of the IC2 power tools", so I figured that goal would include the electric hoe and the mining laser.

**Comment by Timeslice42** [comment]
The statement should have been "all of the redundant IC2 power tools".

Every time I have requested compatability changes to IC2 they respond a couple of months later with "we're rewriting [that feature] in the future, so it would be pointless to change it now." While that does not mean the ticket shouldn't be made, I'm betting the request will fall on deaf ears.

**Comment by draknyte1** [comment]
@Speiger gets them to reply rather quickly. sfPlayer sits in IRC alongside other devs afaik.

**Comment by yznpku** [comment]
I would consider rewriting IC dependence part more realistic. And it is once for all.

**Comment by draknyte1** [comment]
It's a lot of work to remove the IC2 dependency for a minimal gain.. This late in its life, how worth it is it really to do?

**Comment by Speiger** [comment]
Well most of the devs actually hate me because i am annoying to them....  
Also i suggested to make a Scanner API to the miner and the result player gave was horrible. 
At the end i essentially gave up to suggest API to IC2Exp because either they would make it so complex or have requirements that are not cool...
For example: Player wanted to give the ScannerAPI a EU Force that means that they can only use EU nothing else...

And By the way IC2Classic has already a Drill & Scanner API where you can add Items to the Drill. But the item has to be able to harvest these blocks that the miner tries to mine.
Here is the class:
https://github.com/TinyModularThings/IC2Classic/blob/1.7.10/src/main/java/ic2/api/item/IMiningDrill.java
Its a very basic api but allows you to use custom Drills in the IC2 miner.

**Comment by Timeslice42** [comment]
But this API isn't going to work for IC2Exp, right?

**Comment by Speiger** [comment]
Yeah... It wont work because they do not support it.
To make that actually work you would have to ASM the whole TileEntityMiner & ContainerMiner class and hope that they do not change anything....

**Comment by draknyte1** [comment]
Or just ask for support.. So we can avoid fucking ASM for something so minor..

**Comment by Dragon2488** [comment]
ASM isnt hard, but too much for such things, agree. Let's allow GT editing mods at ASM level. =P

**Comment by Speiger** [comment]
@draknyte1 yes you can ask for support but i can tell you 1 of these 3 cases will happen:
1: They say no.
2: They say we put it on the todolist and it will never get done or never gets done for 1.7.10
3: They do it but in a way you will hate... (Especially when player does it)

**Comment by draknyte1** [comment]
I don't care about option 1, 2 or 3.
This simply isn't something for us to consider because it's an IC2 responsibility. If they don't do it, assume they don't want it done and don't just ASM it. 

I personally don't think we should concern ourselves with a machine from IC2 and its compat when there are alternatives in GT for GT.. We've got other things to work on for GT which still is half done or unstarted, I'd considered them more important and if this was to ever be done, absolutely last.

**Comment by MauveCloud** [comment]
> The GT miner is not meant to be a replacement of the IC2 miners, but as a higher tier multi-block version of them.

Then instead of hacky ASM to mess with the IC2 miner, what about adding GT substitutes for the lower-tier miners?  GT already has some single-block machines that are substitutes for the IC2 machines (electric furnace, ore washer, macerator, recycler, thermal centrifuge, compressor, and extractor).  Making it behave similarly to the IC2 miner but use GT drills would probably avoid most of leagris's concerns (except for the rain exposure, but is it really that hard to build a small roof over it?)

**Comment by Speiger** [comment]
well instead of using GT drills i would say that they support a Interface that GT implements...
That would allow other GT addons to add their drills too if someone wants to write a GT addon

**Comment by Timeslice42** [comment]
@MauveCloud, @Speiger  Now that's a sensible suggestion.

@draknyte1 I don't much care what you think as long as you continue to refuse to acknowledge that a) GT does _not_ have alternatives for the T1 and T2 IC2 miner, and b) this isn't a zero sum game; someone volunteering to take this on doesn't mean that some other critical GT feature isn't going to be worked on. And your whole "GT isn't IC2" mindset is a bit silly. Not only has Greg stated multiple times that he has no intention of separating from IC2, but Blood-Asp isn't going to do it for GT5u either. Although in greg's case I suspect he just doesn't want to lose the IC2 forum...

**Comment by draknyte1** [comment]
I don't know why you even bothered with the last two sentences when I'm quite aware of the IC2 split situation.. GT6 does not require IC2exp at all either. With the exception of @Speiger, I probably speak to Greg far more than anyone else here.. 

By requesting gregtech 5 devs to work on this, that basically makes it your 'zero sum game', whatever that is. This feature has a proper process for addition and it's been mentioned above, take it up with sfPlayer and the others because it's an IC2 feature. Adding replacement miners within Gt is the most viable option suggested, hacking apart existing ones from another still developed mod is just stupid. 

@Timeslice42 I don't care what anyone thinks about my opinions, this is the Internet and I'm entitled to them. Most people think I'm blunt, but I'm just honest. 🚵🏿

**Comment by Blood-Asp** [comment]
All it all, this sounds to me like: Not worth the work... So closing should be fine...
