### ISSUE TITLE
Imbalance rocket fuel

### ISSUE THREAD

**Issue by Techlone** [Blood-Asp/GT5-Unofficial#768]
https://github.com/Blood-Asp/GT5-Unofficial/commit/b48613dc7d877db112a0f51587a1583297209aaf#commitcomment-19904500

**Comment by Dimach** [comment]
There is no imbalance. In real life rocket fuel made from water (hydrogen fuel), from oil (methane or any other flammable product) or from air and water (hydrazine (N2H4)). Gregtech rocket fuel is hydrazine, so where imbalance?

**Comment by Techlone** [comment]
@Dimach
I can get 1000+ EU/tick through 2 tier machines and I do not spend anything. Infinite source of EU (1000+ EU/t, 2 tier) = imbalance.

**Comment by codewarrior0** [comment]
Agreed. You shouldn't be able to achieve overunity by distilling air and electrolyzing water. Rocket Fuel's burn value for Gas Turbines should be reduced to the level of the Hydrogen that went into it.

**Comment by codewarrior0** [comment]
Actually, the cost of making Rocket Fuel should be increased dramatically.

The 250,000 EU burn value is okay, when you consider that the same bucket of fuel also burns in an EIO Combustion Generator for 1.1M RF, which is close enough to 4 RF : 1 EU. But this also means since it only takes 30,000 EU or so to create that bucket of fuel, there's also an imbalance with respect to converting EU to RF.

**Comment by Blood-Asp** [comment]
Rised the EU needed for production, so that it is far less efficient, but still possible to make a win with it.
