### ISSUE TITLE
[Question] What is release branch?

### ISSUE THREAD

**Issue by Techlone** [Blood-Asp/GT5-Unofficial#800]
I was confused. What is `unstable` branch? Please tell me your workflow.

**Comment by mura3277** [comment]
unstable is the current release branch. It is the branch for the new Materials system. I assume it will get merged into experimental at some point.

**Comment by Techlone** [comment]
@Muramasa- how about merge `experimental` into `unstable`?

**Comment by Blood-Asp** [comment]
The old "master" branch is basicly bugfree decompiled GT5.07.07 with some missing content ported from GT4.
"experimental" has balancing changes i made and new ideas. My personal continuation of GT5 you could say. 
"unstable" was made because of the huge changes in .24 build, so that fixing small things in .23 was still possible. most issues of the new mat system are fixed by now, so i guess it is about time to merge unstable into experimental and to delete that branch. 
I'm not that good with git, so i hope not to break anything when doing that. I think first the PRs done on experimental have to be merged into unstable before doing the huge merge... but it certainly is again a danger to break stuff.

**Comment by mura3277** [comment]
Might be an idea to add a "1.7.10" branch that is a copy of experimental and then merge unstable into that. This way we can keep experimental around until we're sure there isn't any issues.

**Comment by Techlone** [comment]
Oh guys
I just tried to merge experimental into unstable locally. It's very complex. When you merge them soon, you will cry.

**Comment by codewarrior0** [comment]
Ha ha ha, I just tried the same thing. It's pretty daunting. It makes me think it would be easier to rebase unstable onto experimental and resolve the merge issues one commit at a time.

**Comment by Blood-Asp** [comment]
well yes, that was more or less my idea.
1. Check for bugfixes in experimental not yet in unstable.
2. Make some backup from current experimental.
3. Rebase unstable to experimental.

**Comment by Techlone** [comment]
Rebase? Sure? Um okay. I hope you resolve all conflicts correctly. Waiting this day and good luck.
I got the answer.

**Comment by Bogdan-G** [comment]
hand copying and cleaning or replacement with fixed,, another line numbers and similar incidents, a problematically to merge not crooked.
but again the same question: why it is necessary?
