### ISSUE TITLE
[Idea] Boost Large Gas turbine

### ISSUE THREAD

**Issue by Techlone** [Blood-Asp/GT5-Unofficial#811]
Large Diesel engine has boost through oxygen.
How about Large Gas turbine? I think 130-150% boost will be enough and maybe we will need to calculate a flow for oxygen too.

**Comment by mura3277** [comment]
Hmm. I was actually going to make a "Forced Induction" hatch for the Diesel engine, but I decided not to since it would be the only block that would use it. This seems like a good excuse to do that. With a special hatch for boosting the fuel value of a fuel-mix, we can maybe even allow players to tweak the flow-rate.

**Comment by Blood-Asp** [comment]
Added to collection of ideas.
