### ISSUE TITLE
Broken Naquadah Reactor

### ISSUE THREAD

**Issue by Antifluxfield** [Blood-Asp/GT5-Unofficial#822]
5.09.27, the markIII reactor do accept molten enriched naquadah, but do not consume any of them to generate electricity.

**Comment by leagris** [comment]
MKIII Reactore uses enriched naquadah powder canned in an IC2 cell and returns naquadah dust.
The tooltip saying it is a fluid naquadah reactor is misleading since the initial release from @GregoriusT
The machine tile is a fluid interface hack. It use the fluid display icon with a minecraft fire icon while processing. It accept fluids because it is a fluid interface whereas the reactor does not work on fluids.
It was not made to use fluid enriched naquadah because it is an efficiency gain for MKIII. Making fluid NQ+ would mean: EBF smelting NQ+ dust, fluid extractor NQ+, all this would nullify the 100% Efficiency of MKIII.

**Comment by codewarrior0** [comment]
On the bright side, the fluid generators allow the fluid to be extracted by pipes, so you can get your molten Nq+ back out.

**Comment by Blood-Asp** [comment]
Got the reactor fixed. It was simply overwhelmed by the huge numbers.

**Comment by Dragon2488** [comment]
Well, maybe liquid naquadah will be an option for IV tier?

**Comment by Blood-Asp** [comment]
The mk III was always called fluid naquadah reactor and as of .27 it is now really one.

**Comment by GregoriusT** [comment]
You have summoned the allmighty Gregon, what is your wish?
