### ISSUE TITLE
Worldgen issue with PamHarvestCraft (1.10.2)

### ISSUE THREAD

**Issue by GordonHollow** [Blood-Asp/GT5-Unofficial#828]
Last version of GregTech and PamHarvestCraft

When generate new chunk or world creating with PHC server stopped (don't drop any block, don't see inside any GUI) and console-spammed this: [link](http://pastebin.com/GXhuvLc4) (yeah so long wall just one ERROR)

where major lines is
```
 at com.pam.harvestcraft.blocks.blocks.BlockBaseGarden.func_176196_c(BlockBaseGarden.java:105) ~[BlockBaseGarden.class:?]
	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generateGarden(BushWorldWorldGen.java:72) ~[BushWorldWorldGen.class:?]
	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generate(BushWorldWorldGen.java:53) ~[BushWorldWorldGen.class:?]
```

and

```
	at gregtech.common.blocks.GT_Block_GeneratedOres.setOreBlock(GT_Block_GeneratedOres.java:79) ~[GT_Block_GeneratedOres.class:?]
	at gregtech.common.GT_Worldgen_GT_Ore_Layer.executeWorldgen(GT_Worldgen_GT_Ore_Layer.java:84) ~[GT_Worldgen_GT_Ore_Layer.class:?]
	at gregtech.common.GT_Worldgenerator.generateInternal(GT_Worldgenerator.java:69) ~[GT_Worldgenerator.class:?]
	at gregtech.common.GT_Worldgenerator.generate(GT_Worldgenerator.java:46) ~[GT_Worldgenerator.class:?]
```

Without PHC or GregTech all works correctly

**Comment by GordonHollow** [comment]
https://github.com/MatrexsVigil/harvestcraft/issues/202

**Comment by codewarrior0** [comment]
Wow.

I always wondered why the server seemed to pause for worldgen a lot longer when GregTech is in play.

GregTech's ore layer generator will spill outside of the chunk being generated, causing further chunks to generate, triggering the GT ore layer again, causing further chunks to generate, and so on.

**Comment by Blood-Asp** [comment]
GT alone does not do that. The vein sizes are exactly so big that they will not trigger the generation of the next veins. But, when combined with other mods worldgen that also trigger neighboring chunks, it really might cause a chain reaction.

**Comment by codewarrior0** [comment]
Another thing in the chain reaction is the way Minecraft generates those underground waterfalls, by putting a single block of water in a wall and then letting the water update and flow, causing more chunks to generate.

**Comment by GordonHollow** [comment]
And...how it can be fixed?
I reference issues for better connectivity between developers of this two mods, it can help trying do something with this problem :)

**Comment by codewarrior0** [comment]
Out of all the mods whose worldgen can cause a chain reaction, GT is arguably the biggest offender. Generating a chunk containing a vein center can cause up to 24 other chunks to generate. 

I'd modify the ore layer generator such that three of the vein's parameters - its yPos, size, and vein type - are solely derived from the chunk position and world seed, rather than the IRandom passed to the generate function (which would return different results on the same world depending on the order of chunk exploration).

With this change, the veins can be generated chunkwise instead of an entire vein at once. For any given chunk, it will contain ores from up to four different veins. The parameters of those four veins can be consistently derived from the chunk's position and the world seed, and the ore layer generator can be asked to generate only the portions of those veins that are in the chunk under generation. The distribution of individual ores in the vein can be kept more or less the same, using the IRandom along with the vein's center and size.

**Comment by MauveCloud** [comment]
> I'd modify the ore layer generator such that three of the vein's parameters - its yPos, size, and vein type - are solely derived from the chunk position and world seed, rather than the IRandom passed to the generate function (which would return different results on the same world depending on the order of chunk exploration).

Have you ever looked at where that Random object passed to GT_Worldgenerator.java actually comes from?  I have.  Source is available at https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/fml/src/main/java/cpw/mods/fml/common/registry/GameRegistry.java#L97-L114 (or here for 1.10.x: https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/registry/GameRegistry.java#L105-L122 )

How do you figure that could cause different results depending on the order of chunk exploration?

**Comment by codewarrior0** [comment]
I just figured it was the same one provided to vanilla biome decorators. I didn't notice Forge was making its own Random instances. But that's just nitpicking - the main point is to change veins to generate chunkwise instead of an entire vein at a time.

How would I leverage the Random object provided by Forge to find out about the up-to-four veins whose centers are within the 5x5 chunks around the chunk being generated?

**Comment by MauveCloud** [comment]
> How would I leverage the Random object provided by Forge to find out about the up-to-four veins whose centers are within the 5x5 chunks around the chunk being generated?

Forge provides the World object, so you can get the world seed from that, and use it with code similar to that GameRegistry function to seed a Random object to match what you would get when generating nearby chunks, without actually generating them.

**Comment by ghost** [comment]
Disabling Harvestcraft bushes generation kinda- solves the issue for me.

**Comment by MechanosG** [comment]
Disabling fruit tree generation might help too (trees generating on chunk boundries triggering the next chunk to generate).

As for how this is might be fixed, ore generation would need it's algorithm changed to generate ore per chunk rather than per vein.  The end result would have ore generate in the same locations, sizes, and veins, but would prevent chain reactions.  There's probably multiple ways to achieve this such as pre-generating a virtual map of where veins should lie, then loading only the needed portions for specific chunks.  But either way it probably wouldn't be a small task, especially getting it to match up to current generation.

**Comment by Keyarose** [comment]
I would love to see a fix for this in 1.7.10 as well. I can't add Gregtech to my mod pack due to the extreme cascade of chunk generation.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/issues/1063 Did try to fix it for 1.7.10. Needs testing and if it works it could simple be ported to 1.10.2

**Comment by GordonHollow** [comment]
For 1.7.10 all works correctly with HarvestCraft all time, HarvestCraft issue only 1.10.2

**Comment by Keyarose** [comment]
While harvestcraft is in my pack, there are a number of other mods that cause the same issue. I'll try testing a build with #1063's fix when I am able.

**Comment by Blood-Asp** [comment]
fixed and uploaded a pre3

**Comment by Keyarose** [comment]
It's working with my 1.7.10 mod pack.  The chunk gen cascade seems to be gone though there is still a bit more lag during generation than without gregtech.  Though I don't think that can be helped given what I've stuffed into the pack.  Creating a new world is still problematic, I waited for 1/2 hr just for the spawn to generate before giving up.  I can work around it by disabling gregtech, creating a new world, and then re-adding it.  For now it works for me, thanks for the fix.

**Comment by Bogdan-G** [comment]
> I waited for 1/2 hr just for the spawn to generate before giving up.

you make massive reduce objects chance in gen chunks? Dungeons + veins gregtech ~= game crash or many times loop or infinity loop.

PS I previously encountered such a problem, and the generation of the world was stacked at 5-10min(off 50% gen ore mods + decrease chance/call per chunks/size ore by ~3 times objects + ChocolateQuest dungeons gen when player enter in chunks zone + gt one block ores - off, vein decrese size to 1x1 chunk), despite the fact that there were several mods, and the modpack itself is of the order of 40-60mods (only files, not core, libs, or addons of addons, etc.).
