### ISSUE TITLE
Full item filter blocks further item routing

### ISSUE THREAD

**Issue by GusSmedstad** [Blood-Asp/GT5-Unofficial#831]
If a chest buffer is connected to two item filters, with the first item filter being set to accept certain crushed ores, and the second item filter is set to accept anything but those crushed ores, and any slot buffer in the first item filter fills, routing stops, even if there are legal stacks to move.

For example, a chest buffer contains crushed copper ore and crushed tin ore. Item filter #1 accepts crushed copper ore, but only has one slot for crushed copper ore. Item filter #2 accepts anything but crushed copper ore. If item filter #1 is full, the tin ore does not move through item filter #2 until item filter #1 unblocks, or there is no copper ore to move.

**Comment by Blood-Asp** [comment]
Thats actually intended behavior of GT machines. They all accept only one stack of each type so others still can go in.
The main reason if for processing machines that except multiple inputs. They can not get stuck that way. Makes less sense with the item filter only, but if there are processing machines needing 2+ items behind them it again makes sense.

**Comment by OvermindDL1** [comment]
> Thats actually intended behavior of GT machines. They all accept only one stack of each type so others still can go in.

If I read this right, this is a little different (you are still correct, but for a different reason than OP is thinking)...  Let me see if I can figure out what OP is saying:

* Have a chest buffer that is outputting to a tube that goes to the other two things (since there needs to be a tube of some form between, like a tube or conveyer modules on a box or whatever)
* Have A item filter accepting crushed copper ore only
* Have B item filter accepting everything except crushed copper ore.

1. Put a stack of crushed copper ore and a stack of non-crushed-copper ore (crushed tin ore in OP's case) into the buffer.
2. The buffer then outputs, it tries the crushed copper ore first since it is first in its inventory where it goes to the tube, and then it goes to the A item filter until the A item filter is full.
3. Once the A item filter is full then no more crushed copper ore is able to be output by the buffer, however there is still crushed copper ore in the tube, unable to go anywhere.
4. The buffer tried to output the tin, but it is unable to because the tube is blocked.

This this behaviour is expected, but only because the tube is blocked, everything that goes in to a tube needs to be able to move out or that tube input gets blocked (though 'other' tube inputs will work fine since each is distinct).

I hope that clarifies it for OP.  :-)

**Comment by leagris** [comment]
This is by design with Gregtech filters and you have to handle this with automation and signaling.
- Either ensure no item filter can get full by moving items out of it as fast as possible (deploy enough storage capacity or processing speed after a filter)
- Wire item detectors cover to shut down the source of items before the filters when a filter is about to be full.

I have used the signal shutdown here for this chain of processing arrays dedicated to process ores.
![processing array chain with filters and shut-down signals to incoming items](http://i.imgur.com/Jjm7tsQ.png)
