### ISSUE TITLE
crops naquadah

### ISSUE THREAD

**Issue by natzgzul89** [Blood-Asp/GT5-Unofficial#839]
when disconnecting the world end, no way to get naquadah, without forestry. You need to add fall stargatium leaf, at 3 growth stage.

**Comment by MauveCloud** [comment]
What about the fusion reactor mark 2?  http://ftb.gamepedia.com/Fusion_%28GregTech_5_Unofficial%29 indicates there is a fusion recipe for producing molten naquadah without needing naquadah ore.

**Comment by Blood-Asp** [comment]
the fusion reactor mk2 needs a small amount of naquadah to build. that normaly has to be mined.

**Comment by MauveCloud** [comment]
Oh, for the ZPM machine hulls for the hatches.  Wow, that's easy to fail to notice ahead of time.

**Comment by natzgzul89** [comment]
Only bees help, and if they are not present)

**Comment by MauveCloud** [comment]
Actually, Forestry by itself would not be enough - breeding a Naquadah Bee requires a Block of Naquadah below (which you can see if you have NEI Addons installed), unless you circumvent that by using something like a Gendustry Mutatron.

**Comment by codewarrior0** [comment]
You can make it using Thaumcraft, too. Once, I made half of a Naquadah Dust through alchemy just to make the Node Transducer.

**Comment by MauveCloud** [comment]
Sorry for delayed response, but if I might suggest an alternative to the original idea:
Instead of allowing the leaf to fall during the penultimate growth stage, config options could be added (possibly for every crop that has a material root requirement, or maybe categories), allowing server admins (and those who play single-player) to choose among 3 levels of material requirements:
1. hard (as now, the crop will only reach full growth if it has an ore or solid block of the correct material below it)
2. soft (the crop can technically reach full growth without the material below, but growing to that last stage will take significantly longer that way, e.g. 5x or 10x growth points)
3. none (similar to 5.08 and before, the crop won't bother looking for special materials in the roots)

**Comment by Blood-Asp** [comment]
Added config to disable blocks below crops need.

**Comment by MauveCloud** [comment]
FixedInDev? Really? What commit fixed this? Looking at https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/util/GT_BaseCrop.java I see no such change committed.

**Comment by Blood-Asp** [comment]
I just did not sync the last 10 changes yet.
