### ISSUE TITLE
GT EU compatbility

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#847]
Hello, I have one answer. Several machines like IC2's Nuclear Reactor and Railcraft's Steam Turbine can't output GT EU or even cables don't connect with machines. It's a problem of GT or another mods?

**Comment by Blood-Asp** [comment]
Compatibility issue because of the used IC2 API. GT does not implement IC2 EU in its blocks, but only uses the code to call other blocks with it. So IC2 EU -> GT EU only works with pull direction code. The Reactor or RC turbines do not support that, so it does not work. Not possible to fix that with the current design. Work arount is to place an IC2 energy storage or transformer in beween.
