### ISSUE TITLE
Oregen in Asteroids getting overwritten

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#878]
There must be an issue with Worldgen on asteroids in GT. I enabled the debug to see generated oreveins. I can see ore.mix.copper that is being generated but guess what. Copper mix is set to False in the config for asteroid. Same goes for other veins too... like Lignite mix vein. Set to False, but debug is saying it is generated (and I indeed am finding lignite and copper veins in asteroid dim)

Fair bit of testing shows that even when I have something set in the main list (like Asteroid_false=false) down bellow in the Dimension section it is setting itself to True on its own.

Example:
```mix {
    copper {
                B:Asteroid_false=false
                I:Density_4=4
                B:EndAsteroid_false=false
                B:Mars_true=true
                I:MaxHeight_30=30
                I:MinHeight_10=10
                B:Moon_true=true
                B:Nether_true=true
                I:OrePrimaryLayer_855=855
                I:OreSecondaryLayer_32=32
                I:OreSporadiclyInbetween_834=834
                I:OreSporaticlyAround_35=35
                B:Overworld_true=true
                I:RandomWeight_80=80
                S:RestrictToBiomeName_None=None
                I:Size_24=24
                B:TheEnd_false=false
            }
```
```
dimensions {
    ore {
        mix {
            copper {
                    B:Asteroids_true=true
                    B:Overworld_true=true
                }
```

Yes I have deleted whole worldgen file and let it be recreated to defaults. Still it is happening.

For example Naquadah as well. I have set it to generate in Asteroid dimension but even with the weight set to be really high it is not being generated (spent couple minutes in creative flying around, checking the log for generated oreveins). Down in the dimensions section Naquadah is not being even listed, So I am assuming that it is getting disabled.

Using
GT 5.09.27
GC 3.0.12.463

Log file if requested: https://www.dropbox.com/s/9grqfe5b4dafedm/fml-client-3.log?dl=1

**Comment by dalekin** [comment]
As if the generation of ores (for other dimensions) takes from Overworld's configuration.

**Comment by MauveCloud** [comment]
> As if the generation of ores (for other dimensions) takes from Overworld's configuration.

Looking at the current implementation at https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/GT_Worldgenerator.java#L51 I think that's exactly right.  Even though there is some additional code for handling asteroid worldgen in https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/GT_Worldgenerator.java#L122-L223 , there's currently nothing to prevent the Asteroids dimension from being treated as an "overworld" dimension type for regular ore generation when https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/world/GT_Worldgen.java#L50 is called.

I think the idea I mentioned in #726 of using the dimension id as the dimension type parameter instead of that strange comparison with chunk providers and biome generators would fix this bug as well.

Also note that the special code for asteroid oregen neither adds entries to the dimensions section nor outputs the veins with debug logging enabled, so the lack of those doesn't prove they're missing.
