### ISSUE TITLE
Implementing Greg Tech energy support

### ISSUE THREAD

**Issue by Keridos** [Blood-Asp/GT5-Unofficial#89]
To implement gregtech energy support you need to implement dozens of functions and multiple Interfaces that provide Information that machines from other mods do not even have. Why do I need to implement functions to get tileentities at a certain x,y,z or the color and colorability of my machines and other stuff to just get it to support the energy system. Doing that for RF or IC takes about 6-8 easy to implement functions. Why is it so overly complex and complicated to do the same for GT energy?

**Comment by Blood-Asp** [comment]
Quoting GregoriusT here:
"One Overcomplicated Interface to rule them all.

Colorization because Cable Coloring and therefore connectivity, the Base Functions of the TileEntity to have them available at all times, and the Energy Interface itself to contain ALL the possible Data."

So yes, all that stuff must be implemented...
From what i see, it grew over time to become this way. Currently GT6 cleans up a lot of that mess and that is one of the reasons why it takes so long to get content.

**Comment by Keridos** [comment]
Ok, I guess I will skip the energy stuff for my mod then, I did not even know what half of the functions should give back after I saw their name and parameters.
