### ISSUE TITLE
Reserved IDs

### ISSUE THREAD

**Issue by draknyte1** [Blood-Asp/GT5-Unofficial#905]
Tiles - 750-999 #Alkalus
Casing Block Textures - 57-88 #Alkalus
Casing Block textures can probably be easily changed, as they're not going to ruin any worlds when the IDs are internally swapped. TE range won't be changed for any reason, but since everything new that's been added has been 1000+, it's not going to be an issue as far as I can tell.

@Blood-asp

**Comment by Blood-Asp** [comment]
Always talking about bad practice, but did you ever read this?
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/GregTech_API.java#L68-L92
I know that it is now too late to change, but seriusly... what did you think when you took IDs simply somewhere in the middle? I did now reserve them for you, but that really should not have happend this way.

The casing block textures where reserved and loaded from 0-63 since forever since the casings are always 16 metablocks and casings 1-4 classes existed since the time greg was still working on GT5. The Block metas not in use at that time where just not loaded, but still iterated over.
Because of that it is something you have to fix, since i can't stupidly split the long existing casing class. 
By now GT is even using 0-79. So how about you move to the end and go down with the ids from there? Like 96-127?

**Comment by draknyte1** [comment]
I did, the mod was never intended for release. Nor was it even built against .09, never planned to either. User demand changed that in the end though. 
I obtained many users in a short time, due to how it was distributed. 
At that point, it was too late. Based on the fact you were already using ids over 1000, I just simulated data and based my choice to continue using such range on that. 

I'll just take 300-399 for textures.

**Comment by Blood-Asp** [comment]
The casing textures are only initialized as an 128 size array. I can rise that number, but best not to waste too much memory, right?

**Comment by draknyte1** [comment]
Tssk, now you're being a smartass.

**Comment by draknyte1** [comment]
I also use ID's 30600-30800 at the moment for Cables/Pipes.
So, for the safety of things, I'll say 30500-31000, as nothing within core GT uses > 10k.

On a serious note, that 128bit array will need expansion, because eventually I'll use more than 32 slots. That's just what exists currently, two block classes at 16slots each.

**Comment by draknyte1** [comment]
In the end I decided to just use my own texture array.
To prevent overlaps in the future/past.

Fixed - https://github.com/draknyte1/GTplusplus/commit/dfb374ea275c1bb5e861c5e96fa0688d3b001375.

**Comment by draknyte1** [comment]
@Draknyte1 - refer back to this.
