### ISSUE TITLE
[1.7.10][Compat] Large Turbine randomly decides its structure is invalid.

### ISSUE THREAD

**Issue by xarses** [Blood-Asp/GT5-Unofficial#912]
A Large Steam Turbine reports an invalid structure when:

* it was previously running
* it has stopped
* and a OpenComputers (OC) Cable, or Adapter is adjacent to the animating face of the Turbine block.

![2017-02-27_17 32 59](https://cloud.githubusercontent.com/assets/2107834/23413857/e86ebcfe-fd8e-11e6-9d5e-c77ac110518d.png)

Steps to reproduce:
* Build a complete and correct Large Turbine
* Insert a turbine disk
* Run turbine
* place a adapter or cable in front of the animating face and a computer near by (`/spawncomputer`)
* read the value of `=component.gt_machine.getSensorInformation()` from the `lua` shell 
* wait some period of time (two stacks of charcoal blocks are enough, but a minute or two are not. I'd guess its whatever time the world is forced to save at, but not sure)
* stop turbine by no longer fueling it
* provide turbine fuel again

Actual result:
Turbine doesn't start again, and has a incomplete structure message. which can be restored by removing the adapter, and the cables on the face, then turning the facing side of the control block, turning it back and whacking it a time or three with a soft hammer.

Mods:
gregtech-5.09.28.pre3
OpenComputers-MC1.7.10-1.6.1.11-universal
Computronics-1.7.10-1.6.1-switch-board-event-OC1.6

**Comment by Blood-Asp** [comment]
Thats intended behavior. The 9 blocks in front of the turbine have to stay air.

**Comment by leagris** [comment]
Just a good reminder example were re-introducing casing Redstone conductivity or a remote communication block/controller proxy would be of a great improvement rather than troublesome Redstone transmitter covers.
Monitoring defects and turbine durability and commanding start/stop of turbine is a near impossible exercise without even a block connectible face.

**Comment by xarses** [comment]
So we can't place a block in front of the controller, but that is the only block surface exposed that can access the TE. So I would argue that we need access to the TE elsewhere, any of the Casings around the controller could perform this function since they have another side exposed. (honestly, IDK how that would work)

Alternates are that the sensor information is exposed on another TE, such as a maintenance hatch. Otherwise we have quite the gap here

**Comment by leagris** [comment]
Giving the maintenance hatch the capability to proxy the controller faces could solve most monitoring/automation issues. But even on a Large Turbine, the maintenance hatch has only one face exposed because it can not be placed at edges or corner.

@Blood-Asp

### Suggestion:
- [ ] Add Proxy feature to the Maintenance Hatch so: it exposes the faces of the Controller to deal with Covers, Redstone Emission or Reception on behalf of the Controller.
- [ ] Change Large Turbines and other Multi-block machines valid structures to allow a Maintenance Hatch at an edge so it exposes two of its faces.

**Comment by OvermindDL1** [comment]
Why does the center block in front of the rotor need to be exposed to air?  The blades work around it so it could make sense to allow that face to be connectable but require the 8 around it to be air.  That would fix this issue, mostly...

A proxy block would be awesome though.
