### ISSUE TITLE
[5.09.28] Advanced Circuit and Processor Assembly crafting

### ISSUE THREAD

**Issue by mrTeroblaze** [Blood-Asp/GT5-Unofficial#950]
So, as exaple 512 Lathe needs  an Advanced Circuit or Processor Assembly in craft. They both requires Random Access Memory Chip that requires Wafer with Green Saphire Lens, and the problem is obtaining this lens. There is 2 ways: 512 lathe (loop) or LV Lathe, but with Exquisite Green Saphire with small drop chance in sifter. 
Mad ps skills: 
![madpsskills](https://cloud.githubusercontent.com/assets/26322390/23788796/3bf17ffe-0589-11e7-82e4-e5c43afce683.png)

**Comment by Blood-Asp** [comment]
Even trough the exquisite green sapphire drop chance seems small, you only need one of them forever. 3% chance means in average 33 crushed ores, so 17 green sapphire ores in average get you going. A single vein thats not too rare contains hundreds. 

In my opinion, on the step from MV to HV, doing this should not be too difficult.

**Comment by draknyte1** [comment]
Allow all green lenses, don't force luck based grind on people. It's just stupid.

**Comment by MauveCloud** [comment]
FWIW, the green sapphire lens is ore-dictionaried as craftingLensCyan (not green, confusingly - material color for green sapphire is 100, 200, 130, which IMO doesn't include enough in the blue channel to justify calling it cyan), and there are no other lenses with the same color.

Edit: on the other hand, endereye and enderpearl lenses could be ore-dictionared as cyan lenses - their colors are (108, 220, 200) and (160, 250, 230) respectively.  Admittedly, they currently require 480 EU/t in the lathe to make, so that might not be much help. :confused:

Side note: in 5.10.40, endereye and enderpearl lenses are ore-dictionaried as craftingLensGreen, which is presumably inherited from an older build of GT5u, but that color makes no sense for them.

**Comment by DEMOOH** [comment]
Don't see any problem with finding a saphire vein.

**Comment by draknyte1** [comment]
It's a 3% chance based on finding a vein which if unlucky, will takes longer than Tin. Give alternatives for the lense, basically.

**Comment by DEMOOH** [comment]
Gregtech is about veins basically. It's not that bad comparing to other "vein problems".
