### ISSUE TITLE
Scans from Seismic Prospector not functional

### ISSUE THREAD

**Issue by JohannesGaessler** [Blood-Asp/GT5-Unofficial#955]
When using the Seismic Prospector in Gregtech 5.10.40 the produced books merely read "invalid book tag".
Also the Seismic Prospector accepts vanilla TNT only.

**Comment by JohannesGaessler** [comment]
Duplicate issue

**Comment by MauveCloud** [comment]
I can see in the source why the choice of explosives is limited, though it looks like glyceryl trinitrate cells will work as well (only it will take 4, even though it only checks for the count being more than 0).  The "invalid book tag" part is less obvious, so I will investigate in creative mode and check the nbt tags via CraftTweaker.

Edit: testing reveals the problem is actually with the printer, rather than with the seismic prospector.  However, looking at the source, I can't make sense of how the printer is getting the NBT data from the data stick to the printed pages in 5.09.

My results:
In 5.10.41 (built from GitHub):
Before scanning:
<gregtech:gt.metaitem.01:32708>.withTag({title: "Raw Prospection Data", prospection: "248,69,270,0,92,Light Oil,No Ores found.,"})

After scanning:
<gregtech:gt.metaitem.01:32708>.withTag({pages: ["Prospection Data From: X248 Z:270 Dim:0 Produces 92L Light Oil  Prospected Ores: No Ores found. "], author: "X: 248 Y: 69 Z: 270 Dim: 0", title: "Analyzed Prospection Data", prospection: "248,69,270,0,92,Light Oil,No Ores found.,"})

Printed pages:
<gregtech:gt.metaitem.01:32481>

Written book:
<minecraft:written_book>
Shows in-game as `*invalid book tag*`

In 5.09.29pre:

Before scanning:
<gregtech:gt.metaitem.01:32708>.withTag({title: "Raw Prospection Data", prospection: "62,64,-159,0,23,Heavy Oil,Certus Quartz,Magnetite,"})

After scanning:
<gregtech:gt.metaitem.01:32708>.withTag({pages: ["Prospection Data From: X62 Z:-159 Dim:0 Produces 23L Heavy Oil  Prospected Ores: Certus Quartz Magnetite "], author: "X: 62 Y: 64 Z: -159 Dim: 0", title: "Analyzed Prospection Data", prospection: "62,64,-159,0,23,Heavy Oil,Certus Quartz,Magnetite,"})

Printed pages:
<gregtech:gt.metaitem.01:32481>.withTag({pages: ["Prospection Data From: X62 Z:-159 Dim:0 Produces 23L Heavy Oil  Prospected Ores: Certus Quartz Magnetite "], author: "X: 62 Y: 64 Z: -159 Dim: 0", title: "Analyzed Prospection Data", prospection: "62,64,-159,0,23,Heavy Oil,Certus Quartz,Magnetite,"})

Written book:
<minecraft:written_book>.withTag({pages: ["Prospection Data From: X62 Z:-159 Dim:0 Produces 23L Heavy Oil  Prospected Ores: Certus Quartz Magnetite "], author: "X: 62 Y: 64 Z: -159 Dim: 0", title: "Analyzed Prospection Data", prospection: "62,64,-159,0,23,Heavy Oil,Certus Quartz,Magnetite,"})
Shows correctly in-game.

**Comment by MauveCloud** [comment]
Update: I think I've finally tracked down why the printer isn't carrying over the NBT data to the printed pages.  I'll take a few minutes to test my change, and if it's succcessful, I'll add it to my pending pull request.

Edit: I think part of it is https://github.com/Blood-Asp/GT5-Unofficial/blob/1.10.2/src/main/java/gregtech/api/util/GT_Recipe.java#L1303 checking for a written book in the input instead of paper, but when I tried changing that, it still didn't work 😖 

Additionally, I'm still having trouble understanding how the printer is able to work in GT 5.09 - that findRecipe method is called from here: https://github.com/Blood-Asp/GT5-Unofficial/blob/1.10.2/src/main/java/gregtech/api/util/GT_Recipe.java#L1303 but the printer overrides the checkRecipe method: https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Printer.java#L25 and does not call super.checkRecipe.

**Comment by Blood-Asp** [comment]
So still not fixed? I remember that when coding it for 1.7.10 i did also wonder how exactly the printer worked but sinced it did i did not care... Maybe summon the mighty greg?
