### ISSUE TITLE
[1.10.2] Respect oreDict convention

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#958]
Pretty much all the mods are using Aluminum as an oredict tag instead of Aluminium (so ingotAluminum instead of ingotAluminium).

This is causing the aluminium to not be able to use in mods that are respecting that. So maybe add both tags to GT aluminium material?

**Comment by MauveCloud** [comment]
Are you sure about that?  Looking at the FTB Wiki, it seems like the mods that use the "aluminium" spelling slightly outnumber the mods that use the "aluminum" spelling:
"aluminium": 3 mods: GregTech (not counting the different versions separately), Engineer's Toolbox, Immersive Engineering
"aluminum": 2 mods: XyCraft, Tinkers' Construct

Admittedly, there are some mods that include alumin(i)um ingots, such as Mariculture, that aren't well documented in the FTB Wiki.

**Comment by JasonMcRay** [comment]
Well IE is using aluminum, just talked to @BluSunrize about that and from them i learned about the general convention for using US entries as oreDict. I am not talking about name, its about oredict.

If nothing will be done then I will just look at it as some "annoyance" for modpack makers. Not going to stress it, because I am tired of constant "no it is this way" from multiple parties just fighting over it.

So if something will be done about it, great, it will help with compatibility. If not, we can just do workarounds with MT and this can be closed

**Comment by draknyte1** [comment]
American mod authors should have common sense to use the international standard spelling. Only they spell it aluminum while the rest of the world uses aluminium, like sensible folks.

**Comment by BluSunrize** [comment]
Except neither me nor boni are American. We're both from countries that use "Aluminium", even in their native language, but we still adhere to a sensible naming convention. Go with what the majority of users are actually expecting, and that's American English

**Comment by MauveCloud** [comment]
> what the majority of users are actually expecting

I'm from the US, but I don't presume to know for certain that US players make up the majority of Minecraft players.  Can you cite one or more sources to prove that we are?

**Comment by BluSunrize** [comment]
It's not just US players.
It's people all over the world that learn a lot more AE than BE these days. Not necessarily due to school education, but due to the internet and videogames generally using it over British spelling.

For example, you won't find many people spelling "armor" as "armour". Even I don't and I spell "colour" with the u. Exposure to online media has had most people adopt at least a partial use of American spelling, which is why it makes sense for the OreDictionaries standards.

**Comment by MauveCloud** [comment]
Interesting point, but still not a great justification, because despite what US dictionaries might say, "aluminium" is not truly a British spelling, unlike "armour" and "colour" - see https://en.wikipedia.org/wiki/Aluminium#Etymology

However, there is a line there:

> IUPAC internal publications use the two spelling with nearly equal frequency.

which makes a good case for filing the ingots under both tags in the ore dictionary.  (though for "en-us" language files, I think "aluminum" should be used in the display names)

**Comment by draknyte1** [comment]
Here I'm using AusEng and I'll be using aluminium and re tagging other authors stuff as such with my own mod. Except tinkers. 

Dropping u's from words is another stupid AE convention. They dropped the king and anything else they didn't need to gain independence. Now they look like idiots when their English is different to every other strand. Even CE uses u's and its next door. 

ISO even calls it Aluminium, so.. It's aluminium.
77.150.10 - Aluminium products

**Comment by Blood-Asp** [comment]
I'm pretty sure the only reason why "aluminum" is used as oredict anywhere is that tinkers forced it's usage. In earlier days "aluminium" was the standart oredict.

**Comment by draknyte1** [comment]
ISO standards are the global standards and they use aluminium. Simply because only one language uses aluminum.. Which is only a strand of English, it's not a language in and of itself. With the changes made to btcher (removed the u in butcher) words, only Americans think American English should be used everywhere*.

**Comment by MauveCloud** [comment]
> ISO standards are the global standards and they use aluminium.

Only partially true.  From the Wikipedia article I linked before:

> The International Union of Pure and Applied Chemistry (IUPAC) adopted aluminium as the standard international name for the element in 1990 but, three years later, recognized aluminum as an acceptable variant.

**Comment by draknyte1** [comment]
No, my statement on ISO is correct. 
IUPAC also had aluminium first, only accepting aluminum because there's a country full of illiterate folks using AE who can do science. Don't cite Wikipedia, cite wikipedias sources. Anyone with enough approved edits can go change that without approval right now.. Unlike the sources.

**Comment by MauveCloud** [comment]
🤦‍ 
Whoops.  I didn't read your post carefully enough.

**Comment by MauveCloud** [comment]
Let's get back to the point of this issue:
Some mods (such as Tinkers' Construct) use "ingotAluminum" in their recipes, while GT5u only registers its corresponding ingot as "ingotAluminium".  IIRC, Mariculture, at least when played together with GT5u, registered its ingot under both names, but used "ingotAluminum" in the recipes, so when GT5 Unification kicked in, the ingot was unusable in Mariculture recipes.

While I'm curious which other mods use which spelling when registering their ingots in the ore dictionary, instead of arguing about which spelling is "correct" or "standard", or trying to convince other mod authors to all use the same spelling, it might be simpler to go ahead and register the GT ingots with both names.  (probably not worth doing for other components like plates etc., since afaik there are very few if any other mods that would use those)

I'd add a change for this to my pending PR if I could figure out where, unless somebody like Blood-Asp or Greg can provide a reason for refusing the change.

In case it wasn't clear, I was never really against this change, I was just uncertain of the premise in JasonMcRay's logic for wanting this.

**Comment by JasonMcRay** [comment]
Ingots, Blocks, Rods, Plates, Dusts and maybe Gears would be definitely something that other mods might add. I can do it with minetweaker, but the auto-unification with minetweaker won't work (i would need to minetweak more processing recipes than necessary)

So yea.. the reason I would welcome this change or addition is like the main reason GregTech does all the unification... to get rid of duplicate stuff, where I cannot use plate from one mod in the other mods recipes.

**Comment by Blood-Asp** [comment]
Double oredicts might be a way, but changing the GT default oredict not. 
At last that should be not too much work. Like 2-3 lines added. But not sure that really nothing breaks because of this.

**Comment by OvermindDL1** [comment]
Double oredicts would be best I'd say.

But I have to ask, who are the morons that spell aluminium wrong and how are so many doing that?!?  o.O?

**Comment by MauveCloud** [comment]
> But I have to ask, who are the morons that spell aluminium wrong and how are so many doing that?!? o.O?

I can partially answer that.
In the United States, "aluminum" is considered the normal spelling (and thus a case could be made for using it in the display names when "US English" is chosen as the language):
https://www.merriam-webster.com/dictionary/aluminum
and "aluminium" is listed is being chiefly British (although I'm not sure how to justify that claim, considering the ISO and IUPAC standards):
https://www.merriam-webster.com/dictionary/aluminium

I'd have a hard time putting together a complete list of which mods use which spelling for the ore dictionary, though.

**Comment by OvermindDL1** [comment]
> In the United States, "aluminum" is considered the normal spelling (and thus a case could be made for using it in the display names when "US English" is chosen as the language):

I've always lived dead-center of the united states, hick-ville basically (think texas), and even the teachers here still spell it Aluminium.  ;-)

And yeah, in the ISO and IUPAC standards, Aluminium is the element name, there is no element name of Aluminum, and nor was Aluminium ever mis-spelled in any such way that I recall here in school, so it is what should be used, only.

But yeah, that is just stupid, chemistry names are Hard Set, there is no weird ambiguity or crap with Chemistry, and these are chemistry names.  Blah, as stated, they are morons...

**Comment by draknyte1** [comment]
Just force other mods using aluminum to be retagged as aluminium.. Better than trying to support morons.

**Comment by leagris** [comment]
Do what works best for the player, end-user, mod-pack maintainer.
A mod is not the right tool to enforce rules or arguments even when you are right.
Gregtech and other Mods have been seen trying to enforce stuffs in code just for the sake of this is how it has to be, or stop enforcing your rules on other mods.
We all knows how it ended-up.
So, please again, think of players and mod-pack maintainers perspective first of all.

**Comment by draknyte1** [comment]
I suggest speaking to @Vexatos for TGW support, it's more of something to fit into his mod which bridges the question. If IE doesn't use proper OreDict, then we're out of luck, otherwise end users can simply add an Aluminum tag via minetweaker for whatever Gregtech content they need to use xmod. 

This is a pointless discussion that won't get anywhere, so I see no reason not to close it after offering valid solutions for the two offending mods.

**Comment by codewarrior0** [comment]
For the record, Galacticraft puts its ore in both `oreAluminum` and `oreAluminium`, and also finds all items in `ingotAluminium` and adds them to `ingotAluminum` and then uses `ingotAluminum` in its processing and shaped ore recipes.

**Comment by Blood-Asp** [comment]
I said to add double oredicts, that should satisfiy everyone. And no reason to discuss more about what GT does. The other stuff counts as offtopic to me. US Americans do strange things, but we can't change that.
