### ISSUE TITLE
Fuel values arent being displayed correctly

### ISSUE THREAD

**Issue by JohannesGaessler** [Blood-Asp/GT5-Unofficial#961]
In Gregtech 5.10.40 fuel values aren't being displayed correctly with JEI.
The fuel values are displayed too low, outside of the window.
Specifically I'm talking about the tabs 'Gas Turbine Fuel', 'Diesel Generator Fuel', etc.

**Comment by MauveCloud** [comment]
I can't reproduce this in my game.  Could you please provide a screenshot?  Also, what build of JEI are you using, and what resource packs are you using (if any)?

**Comment by JohannesGaessler** [comment]
![2017-03-14_18 25 37](https://cloud.githubusercontent.com/assets/18492268/23913687/fdbdee58-08e3-11e7-8e8b-9fb91f4655db.png)

I'm using JEI v3.14.5.406 and Forge v12.18.3.2185
I still got this bug when I removed all mods except for Gregtech (v5.10.40), Industrialcraft (v2.6.142-ex110), JEI and CodeChickenLib (v2.5.6.224)

**Comment by MauveCloud** [comment]
Now I see why I wasn't getting it at first.  I had my window expanded, and was using "Large" gui scale instead of "Auto".  However, the way it's implemented makes it look like it would be impractical to adjust the positioning of the fuel value - it's an extra line after hidden lines for usage, voltage, amperage, etc.
