### ISSUE TITLE
High Pressure Steam Turbine outputs

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#98]
High Pressure Steam Turbine does not produces IC2Steam or Distiled Water but (normal) Steam.
So we cannot make closed circulation system of distilled water.

**Comment by Blood-Asp** [comment]
But the "normal" Large Steam turbine turns both steam and IC2 steam into distilled water, so a loop is possible.

I used everywere the RC ratio of 1L water -> 160L steam instead of IC2 ratio 1->100 but only using GT machines, a closed loop should be possible. Otherwise a machine accepting RC and IC2 steam could be exploited to produce distilled water.
